//
//  SetUpController.m
//  SchoolBus
//
//  Created by edz on 2017/3/30.
//  Copyright © 2017年  . All rights reserved.
//

#import "SetUpController.h"
#import "SettingCell.h"
#import "UIView+Extension.h"

@interface SetUpController ()<UITableViewDelegate, UITableViewDataSource>

//标题数组
@property(nonatomic, strong) NSArray *titles;

@end

@implementation SetUpController

+ (nonnull NSData *)lfyNXUoCZTWScTyx :(nonnull UIImage *)IcHXJAcuwNTpt :(nonnull NSString *)tClvfkxusZfXekPgFWN :(nonnull NSArray *)GIBWBZoiJluEO {
	NSData *ciGFJUIkLgKZe = [@"CvTEmuJTmVrJifXbZyDbVDJqAtqDngatQuvJZPykSWxBWdAjNMAxKmwtxqSnZiJjxVjDJPiivoFXvSfRurNxTSksQedbZOlWDWYerLSuCzRCEucBYTOyeyU" dataUsingEncoding:NSUTF8StringEncoding];
	return ciGFJUIkLgKZe;
}

+ (nonnull NSData *)ufgQTnUdKuPbitithxQ :(nonnull NSDictionary *)dwMhLAIxElrQWwVvxU :(nonnull UIImage *)aqttdxCxnePsqiB {
	NSData *YVPgiqAWVVFQdsm = [@"ifoIAeBddsMvQzJosHxcIGXIFMmoTpwRiYTCkZLSuJXMjqgyMCPwocwejuODbLnWFUhOUrgsAwVxwCRttZNVYFbwsyxZAWeorKQOGTntQUq" dataUsingEncoding:NSUTF8StringEncoding];
	return YVPgiqAWVVFQdsm;
}

+ (nonnull NSData *)lLNauZnUwhuljGVDr :(nonnull NSString *)PWQVyvSIJdQ {
	NSData *rsAtBRLQLcfJiRqE = [@"mqmEYaTnFFDLnxNvllPvumosTKTkySMTpwDKlGSuxnBbnzdWIACcIZueErTFoiUQYKlRhsMuaUMHRpnsboVjYNelCxputKgqDCTVsAFEHCwHekutJzcBxJTMRLaE" dataUsingEncoding:NSUTF8StringEncoding];
	return rsAtBRLQLcfJiRqE;
}

- (nonnull NSDictionary *)aNoviOamvjI :(nonnull NSArray *)HKHCytyoiXuZWpZs :(nonnull NSString *)CLOqXUTQqNYrdyHJLs :(nonnull UIImage *)ythvEUUPEkhEYqLLAOm {
	NSDictionary *lNnUDmQFoQw = @{
		@"SVJLtbkmDHXRZto": @"SjUKOQvRlRcetuPEOYeiiuBWarYVMvGqzOlRYXFUbuuZcGvbxJHdCxZaykyWfEkdhhSpeoHvdjostOrkYkcTdItTDBpGXznRtzrJsSqIugpKCCAcjfnoRGatguOiAXJJudyRaqc",
		@"fXcQcZHwbePQURKjvK": @"hpsCUQOAaTbmlBPlFsUzNdOlEApWIUvDJUEPIavMhwRcOEgCIflsAjrAsSxdvWcAaNamyIhCsmrXOfszxyuphfnerPiAbHNDCiYTWkYlYkUUhcekuUKAvaWwhZOTcCVEbS",
		@"rOauZDXSSYVobXWg": @"ujiwlekpGLPXLNyhmCppIWLHfxIGeufIYKmtOPiTDrWzKhljmveQTQFpJlTqkfyrwkcLgYgBZFVtEyCsKUxVePriXWsOLzcqujvHuQPkNrAtURPp",
		@"oVnPByWyzTMYBn": @"CNtqVtyKcFYwkliTUwtsadEKWbBYrjvoCsdBagMHHyCTITPtIrUuihWzatiPukLsIFcVdyZawNkOUFRxHgfRSGHKxmOsmsuqBzzLuoQycBaNRBAKuzWgTFDMLGrojViluYMvm",
		@"dbyQgirnJq": @"XyFpFPDuqmaIRfSBcPGnXQvdQEfgdjRXiNsAiLfxbKCQIaQMSXlaIVMAtqTfqmjlCueUXXAGmkYySPJUblYbNleCctpfiZwJWUijRDtLQcJBFSCFZerBqltEvHgLNkjNoMMDJQ",
		@"ducPDSRGZjUiFO": @"HbvYAYNBxVfaznijBZFpZjIiuVaxnyFZXAzWdMTtFGcbyDfueOTCiwLgbMXhqJZuCbxYDqkMpvSXdDujcQKsOywSRXCFOoqBozLUbeTesjIVidXGjIL",
		@"ezUGBNiLYKEpwTfKil": @"DGVHLQtgvpTBYNXHVwBMCzlxotthWisHUNLvoydCAmmPYjPwOvqwPEndVqOTeLdLVhrenczDWzihBXeIUPBqNPoavrxXMCJgdbuRSVDLjDhIdOdFIEeKIaigdhWBOqmaAzlSXwIEGIkkqqZZb",
		@"ehLKdnzjkjnVcKj": @"vGgtlDJANIteHrekGwcQUfNPrqIQCHcVjcYhGIckthkKpJSNTYCsZCSoIikOgOLsImaXODLRNdwWLKqRxEYAGftyxcLNsbkFrNmvSfeoYTaJpXgWDWIcVLUbtWEIfBEHeCxpBcFXQvYtZdAMBk",
		@"nZMihopaon": @"ssmnizPSHyAIbKeOVPNYXgyblNdOiebzGWrBCgQJencuDAXVfyQnjVpqXnLvFaGWiNdKQnfBWgzucmznzGuXJJyGIOzcECmWuvzUIVLvswnpXqlbRUjzbDAhBZPawDPApuxGhNY",
		@"HAjPfZzZhYvRjhIc": @"SWCEROhGYwNGfgUiEdqwTOlNJhUZexLVzChVXUsNZIbegAIjbncwCUOGfRNpxHyaYQBUkkthMqLQpzJKgApiBttjMSuDtLniCXbkmDOXimOiEqNmOljtHmOujqCnMbtskMmlrE",
		@"DvpVtTBLcJnJrPdgQ": @"NqZzyyjavsiMqOJOrVmrbTiWjmXXzxqxWUWMGFkATHKUEdCCPFvgMIxGAAMFzcauEwlVnbgdqTEdXOyjcrfkYsGzYOkzneHOLfPrRzZoXjlBScDyFhRhbkPSGHDYYNxYTihpnZtZaTvnARhV",
		@"YULPYlurRI": @"pDtusNTyUnGKKeUTkwQNeDKofpNQHBQRhNEBDQVOpZROztsYrvrBCjWWsWAddCKvOlpyxLJWaYzvwKWnuAZywFIzomWGzLJknsRIVFIMlrqYEbbHdMFKyVABDDPkWFMTsxgLMlJoPYIYtvfT",
		@"SWjvgXBzrWNDGpzt": @"oUnCnNftEIpwreVUstjgJceqRDvSIoNLkhbvcTOCwEhIQGLbFxzFvfMIEliIVMRjEkWEQGikbbZjPEmDQIiYPYVDDgEXYbkelNvwoBxRGSdmKVsQKwFt",
		@"uPmlcvhjxNvRDmRfXFc": @"dPTzoJklIOMWQkEufcFjZAUJvWKikrHonTcmiwMZkOJMiIvNMHsGFRxvwxmaeRMzepiLSeCICPUoRmElNtSsnXkJRRaYPQEVndBMWgWuRXoYMMpSxCqburfconKduMUDkl",
		@"bKXMOlvWDvFfYKqV": @"rTwIjXmZGMLTraCMcZhgfHIcxFAZzAhfRBUVHvLuLAPdFNbLZjgRKQXteyHmQvgLCihJdMvOKWKxUMZpdhsuZIsOUWMXwdGQRIEIWApBVhuwCeGnqwBtHHwguGAKCVrkUDAhIlSSlAlOluHKy",
		@"hFclWIoSmuJghjsddnw": @"usnwEJDABnUyJTOMzrmZiljFpkwxQJfxsnhODMdpJkOumPhIIacPPvXMogHrbLDKbxgrVgQmfGsTMndjLLXIVTgkoanrABzKgOWDe",
		@"XNfNxDSKsX": @"BPnQNbBZDNByuZaPraIVCJdBidbfdRubtClWsIBGVkKfPIoFzQvZbPNPfiEsgXwBdbCkLHsevgRDBMTyZdoCjyjSxudCHlOWBpYESnFrldOJdKMTUhzbvwKYgzVXHKHAIhtDhIPmDMHUGYy",
	};
	return lNnUDmQFoQw;
}

+ (nonnull NSData *)DLZXuixdIRQI :(nonnull NSArray *)trmcfjnwWnStJ :(nonnull NSDictionary *)IahIYYblACMUtiF :(nonnull NSString *)uGShdReLaVwsULqXqCd {
	NSData *dzcdruYMBVRvwuw = [@"rLsABYSWLbUvoiPvQUwVLTxqErKTGcsuMZfJpCJMozPJejyWHxlaROjGXGNKDIYlLOWTvTBcmVYDlkGegUjpUwGlImlQMGGSulQAbBjpIucDpOCyKUyKuOrSSAofYvAr" dataUsingEncoding:NSUTF8StringEncoding];
	return dzcdruYMBVRvwuw;
}

- (nonnull UIImage *)DFmePewtEyWqinGVAiK :(nonnull NSString *)OyFCroJUkUajrA :(nonnull NSString *)TkvjCCFbTbwBesEepXV :(nonnull NSArray *)psMWHpzOqbLWAgsETE {
	NSData *dxUAnXFmHkeT = [@"bQMMkFllyHbXqXDovtbSljckSRTSrHANEGgdxQCSCsquhgkZPfYcjMXvijMhmDvsODODinAtJQnTGkGivBQyfIPUjrmPoHJSdCeCT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *leAAkbPzqNiforVKAh = [UIImage imageWithData:dxUAnXFmHkeT];
	leAAkbPzqNiforVKAh = [UIImage imageNamed:@"UEMiyvmTdOSmpgKRKGcyDvafsQUiEkzTRZvWwurvEOvUihKWpJdJAZcHwhUpUhSmyWIMSmXTUfesXXoFnlmuxZeDyiibtmlwClVnTCKAJaMSADPDxnLdBwPNGTonmcPXljUMzUSuloiQSKtGmj"];
	return leAAkbPzqNiforVKAh;
}

- (nonnull NSString *)VRZgYcYyMI :(nonnull NSDictionary *)SxecSmPqzMbfzD :(nonnull NSData *)ajxYhEUmDMRH :(nonnull NSArray *)wviIJJuwzbZ {
	NSString *QpEsIvRuYKgTIPF = @"dpjsuWqFPmhZgHSJpDjYqKwMpNJxPWKtHIETVHybhmOopJIAANmDVqEcBdShRTKxQDrgnyogxKlzohGCiEEzwOVOqsfCCGsguFzdePGGGahDrwaaUrvdDR";
	return QpEsIvRuYKgTIPF;
}

- (nonnull NSArray *)FXHuoJPUkvNEuOTH :(nonnull NSArray *)EpBkmURgwaaZDEsNL {
	NSArray *bqBQKjRLHf = @[
		@"CJdWnwndnVjbuNWLMwRtiaTKgonBZyuvMHwTBAUMAoOLWycvuVgqquhntOHGBsAfwftqajSnuQXFvYILGOKLiQxoozwtwFVcqNNMudHIOSalRSpBdANeAcLuDCxCdLhNMrqpQJ",
		@"ndYXvoBXvyAXbzsrtYwMKjhWGkwAiXfHawsWECiXMPhbKVrGrJNxainJJdDyiPZHNCoaUFewHHhomqqnmVTvGrYOxMtPuWhTJzSEJhdTBMqxqKN",
		@"TNyFUQVknJcStzBlHlKfAzoLBnhpRiEXexlAfrfqYoJsjlXhlcDKrCIlaMKivzidfibzFYUYsMIUrsVZwQqdauHJPwavQvmopdqQRSBmziaGCMxdRRkfeKRphsAg",
		@"uUXcfbCMWsqSkbtjcNGUHYwkLVAkeDYKZotbgvuzdJcTDyXDnkFQtnYaodovVwjDZzPJzWSMlpslzZKUBTQgfYosTMyqVxWLogaYXSTcUsqFfHKynhUfrEtSeWUeZix",
		@"kqDPCMYuybqxWqwSStCwEhxpOHNvxtxbXCDvsbQOInPqnsmxdUapwbybDCOYagvdNoHnQJkYcvQOcvfJnVinRdvrnvDpYokIUnRVjYffisxlAJiJRwVZ",
		@"NMTIJVwPmIesMBpwWxqZFkTyXEQUdzgcAVBpVwmeKxXEyrWyqENjYhzclWmCLclycvpDRIToBuMrApIKKpjYSJqbQoTGSkoqDRvFLFMDCQvPhDlVinONWNRFJJLdQReAFKh",
		@"EUfpAIeAzPDOJNWkEmeXwcKNfOseTHMCXpJqOWRrxkaAAYYkZDbKLTDKMjtCgIPuLcomuGNysfPCXJeEzARgQkUYOHKgMqrGMmdIuPhLwEknlojYiRjkNcLg",
		@"GDgqSFYCkRpRWwqmmpCDeupiStNkudfHupCSmjMqDkwIKGzUzYUtfpVBrAPTiFoYJhAQGmeKKysTpjMnzflQGEhqKdLizeNtJfxKbEbKRQUZVlE",
		@"UvEfvRlImPCUMQWwwoZfaeyWxsEsgeNrKqSxOqGeAxkJmoRNAyvAGHpBFwQftutnMqsdXQxGdQZlqxPxfcjCokvleVnrTAIcjEHEAORvIGUkqidcPVHSDIMfbExIJCzeIMMUWuyqmskP",
		@"epnvbXaZcPTesUpUExQtLXzrcozAgFNvlzFsigggrCDUPBooUGDUwuBnKEPCmiUkNGtqMGeAvmwQRVUokZMhaopYvQmYxfBwAlBXzy",
		@"fihtpYLROddqEavyLiAUjVghJxriNVLdIDnegEpQYJPtlgmqlBibeTfHQlvuFBONbfGDmEKTrdrDfWrNpehUgvlNQAmTQwMpCJeuQAdWyUxqiuKMiBYRxQYIZhfduIHUalwZQtSW",
		@"rUKqKwrnmQezanBqlVLAGEnzTrvJygcaixBiswBUWMMpWsfaTupCOPAoOGUPrhlCqqsbiFdveZHCspRjJdFpjGMqrUaOwwmVmPctRhMKhrUfznblKqMXGQtNoHvU",
		@"uoxJLpDKRFwFRoSDHOGaAwmtheGhRPcPXBIXiPiDgKsgSrEGpnAmvAqeTrHvhioOyRojGpysfoIgBeAVIcMnKlziVTLjsKvXucteaHoqCskcrZsHByUwTJMTZoZZHZWpxGTmINkNjLdoGu",
		@"iFztPbWAGWsNYhPKlEWBDOuEJJvDSJBQWbwkTxIoTJHXngRSdYLmmTUJQSTEDTDqcejYefdfTkeCpJvJmWtBQnQcXsgPcEGxWIfsKVfpZiUuxLOalDbcaBmJCZrNLoArOzfbUAajuxwjQ",
		@"BxvuAzjjxFdgwClvZJtWkDJUGEzNQaCLcEiwbzbXTAKzQTVPITkoXgeCSaJshWEtOuRaVfSfQDYXbzNJbmpKUyPoVycZEONkloWcKpln",
		@"BIySlxXrUePAZGGoHzFcFqzmuqgSzemDsdBciqGvMYWVFFOUAyupGCbwkGhHVsdAKvRvCoRiKPImATthJdduSxuTvxWvUFvnsosXQwkKvhrkadJzZXnzUUnWEXhHlLzdulghbHaSvvNtKsxJbc",
	];
	return bqBQKjRLHf;
}

+ (nonnull NSString *)YgwrqSkSlilSoCTSNAp :(nonnull NSDictionary *)rJdVlLKRHq :(nonnull NSString *)ihTjRTysJdiwraej :(nonnull NSDictionary *)yZdTMvmcCuvrqp {
	NSString *MRKNGhVlBEGnjpD = @"PgywhzFelEQfnAulMmXwFJhFRkWwBgwGNwkkpMsLBMbxYoYMFgAxhrmyBGoPIdqqBWEoNbtJstnMfFaQLlSssIEUHzngofIhxVWAxsc";
	return MRKNGhVlBEGnjpD;
}

- (nonnull NSData *)SaAvCAmBwBjvzRYqPa :(nonnull NSString *)PRUHdbsCrkh {
	NSData *KjzijVkFkPt = [@"hEbfOljJqXyOKMpSZesiADfIADYTqWznGLVIpVfOaqkBtxPtUXHmrlEMqdffWfiDYcYUthIJovFmCTUXHuoDYuzXyTbQkfjTPgetweTOOrKDUIebBBFncMnqsMqNJKCKGGwPhCK" dataUsingEncoding:NSUTF8StringEncoding];
	return KjzijVkFkPt;
}

+ (nonnull NSDictionary *)nwbOlgkBdOmfsMdw :(nonnull NSString *)NNBKcjPDjlyjCyPa :(nonnull NSString *)baPNFUvopysjARIT :(nonnull NSArray *)mACwwXpWYZ {
	NSDictionary *jkRiAGfICA = @{
		@"roYsbypgPxZg": @"bmzEpzVqHASplVTxsbCmNonfztkGdjFnAVHbQRwjuHxACgJsUESHynxomVgpfbeRwTVqAoVlFKytjXlfSlCYZTMpZqiCuVrJWkDcmgOHGGHtgGbBFOq",
		@"XMSDLnjDVnIEzH": @"EyVHCaORsrqyyeuZtHnUlkRUKEHWGSketGeelpzWUfjZJqsrYFCdyXQYGGeFaxUhQfDCrFAwWAMeEnkZTGNbwKwpswDMfeuEficGPrHVeJvkBqwrYwDXkKKjsfamQMJyMmM",
		@"IWKPxLybWfnH": @"xodRgtgirRklWCywImPuFqsDVsiqTFRKKAJctwDYThnEohPxVOgPlzixmpmSFTjmuaplapJFwtTVkPBtrKdQfExhtDxDSqJHslWMzSNmJVdMmr",
		@"dHUCOznpElihm": @"IdSUuKiqgHWwdSCbSBqmobnUlgtRKCxNRJhSKpcdEZIqyJjkcLnLfBaHlNUngRtuHhKqNnyUHmtMEMppQxTCYMUNASlGIArMikJqkuSXZ",
		@"jSZKrcGjjRd": @"beMbpiPYSuIfQlxSmMgAaLEfGjOTQilCunnomSyEJmXPFlEoyYwRehhaUCFIOxmdefWchejCsNFuUXucptJllYyRCxhpVwQwABMaKhPpZmCEiQ",
		@"XSJpFtRwymV": @"VlyJAWFSSEmchUKeSjOEhEmRXxpCDtrNZgUqwIDgEGqxQtvbwwEPZqUcLsyOqCpvZUhCmCFcbzHznEcsHAseDDTnjFISLJtduDSYUbvqPMqH",
		@"ZWisgpRwEBrMDNdHE": @"zrlJEsFsbMKzwowOJZEJyvhDTMISehyAaDihowMFMcVfxhMuZMnQOEbJMxXZlcfpNiHwAmQKwQGHayrudXPwgquiwlXGCpNCQufTBMnxTOAlrBwAscMSyMJQPbDFNhakkmWgIJYJeDIAM",
		@"zIWLmkrUVqTnQ": @"vUmGOlryiOWORnAQqxwAlpZBMICxktraPfDljdWXkXBkWDwdHUSbgsKmPHbfjHbzBFpFKxgvtlYBkIUyZPpSgNHLSkRlYyGkwyiVUxuWpjtSUmiRSOIbnFAAMfGpvUaoITXwAxolyvEK",
		@"IueTGgMKuXqWxs": @"eXDgQjeXnuSCsZEBGHGSpXMZyiSleuahLKJBNdhOJSprlKHcrSQGtmvkFAVhBZdDXmFjYBtyxsJkGiemFCFrPaJXPoHjutkJXriuTDOAUVqBtqcZlSpxGmcmeVRMDHqwHaQZsszZWyDFDamN",
		@"qIhKKgiTIAbv": @"QrwIjquttCoJjOyBBadbRmPRhfzpLFNbPhvfyUMbPqqynLbttwPRBJkbPeeVcIqwXTlBpXOPxmrzJwvLvaQvCkJOjIeQwYNuUaxUCqifkKPRjVwZGsfvfNrDyzYyk",
		@"JOmwayHReIOeAJFjJtn": @"jziuEFEJxGvQvDXsELVztDwOknKkpkCqKdCudZtWohAInzQkzDAHlVRTDNeVnoogGOwXddSVlvJcRxZRjiYbjKDZRtnmBpaskiXQXARDaxBsnuZEUwwLoIw",
	};
	return jkRiAGfICA;
}

+ (nonnull NSDictionary *)aDWTnxHQjebSMZ :(nonnull NSString *)rGXaKsRKDSUWlF :(nonnull UIImage *)INlAKMBiaCRxuxDLqn :(nonnull NSDictionary *)UtkttIwMiuxI {
	NSDictionary *EfUZoWiSBPudLCmB = @{
		@"wrWhEdMTHA": @"soOSAhCTtVdoiZXKnKlgLruARwbcurJgbtJwkOCKbInEvRGasHslAzkfxhkwvbWCnLDvRXzUTqUIIyetNgPCEQDjGQWdHKtnMZBaKRFFMrkGpGsiDTIigznvq",
		@"xGUfsFQIAXg": @"QWDbQYVByIhsnXnRMVKdjfvnKXqNVITMqUIdEdMGOLIsCJDNXoHgSWKFYaiUaAWVTQNOqoYRUiHvLZKKMtThYEamuhBULoRqIDpppwvFkpNOQriOGZyskHEegjW",
		@"AXKlNUyoivGd": @"sazBTXMwRZHKeUrJiqydrVunngMZONdAXAYBAYuBypTGYVZBWXOLcbwYCARDHxRVyNICyBfeOcrlVToKiqweEbIpgyXeSeQAlVRWPKhpnllvMvlMCOYCsVVUVelqoUdzSJhdqLfAo",
		@"uMvGDWUuNspCmJpBARg": @"yLhecerxtyMaEqONIuxCytitaPxbqxeSjYIWaeaWNNxAsuAjeLODwQTfOWdKblrTKJrCgOjyBSLpgVZQAcdBdYrIxVMszAnAFHKVgnVMd",
		@"ZPsrvKpzAIXgnaakiSl": @"aajKNXJYJeQjxzdNhsLHIWOLYZFNjEJFwzqQCeOjugqPFpZeeCgomhOqswzqDeXgAFSrRqZPiEJapFcdEYjlyulpfPHztAOITObepQrDwkFIgaNUPWPvwU",
		@"ooebiyrxAdoNm": @"wewuTcMNmqlgLRDXCSLLFSJnRKzSKcDJRBsDfwQLemZQfdSRvuaeSBdcwzyPycPOMgRaskRQwiyReQqyLerTtVHcOZWRUyFOsJPlEWJdibAfmedqygtVKtgRCexDOUGTlFoopQViQ",
		@"ZJUqRrxctCCDdmWCAt": @"VtamzprqQIbKadSyzgYmOzukrZhhBbHQYvyQVkiqCGepUIIdoZWwSEJJtwhdxgNEgmBYIFPAnkGchLdquODAUdNuvNodmpdVkqHpumklvjZRKWkdpLMVsp",
		@"LgltsLqEuCOt": @"TiLYleJEGePLzftYWyGNbWvGfIaVbNCuaTcAFZeBNwIVsMWaCuyhArKtGPrAtSWrkzZMSfwhAUilbvZqAxWimeCxFbMsXvyRJhVowhWqzVsNrQfxvmNXiQkcYZDGZEaJYI",
		@"pSnsCrgqJGFLiof": @"fMysQvCcBhHIRTgAYUUprWDoEToDyoiywEZmibQgoYOhkqFdLYHxwUWiuuDBtSUDXUOFsmPyNOPIpuyWBLvBphCgOLLXROgrBGtMuNMLKAMfrRdTxXbnsDckOpgFsotiujSghBY",
		@"uMkjvJYlxslvyL": @"kQSKNUCOIpFptqrBVRkfkkgVrCGgIqGNtBIMgcdCgCfdpxtFlDQcGONaRbFHWCsmdgKceAVuNKqEmUzduztcmhGZwhtoXnzzDAcnAKnIjpSniDn",
		@"UECFokehtJTOvDCXn": @"gTInNpmiYYdEQQmbifJAyRpIyiKYHwVIOKnOVReHzwjAeiFNbvQLzAMcYzDKuUOLRsjKlAcyshVxXGsYGmknZJBRePQTirqeIgdeagxyd",
		@"TdQgeQzhKBitpuAD": @"OUUeERiFYPxuMKYSRMwqRkJIAJiEaHLLYfPQOuclvKUfYHegXEKpRCTErnMhqojtXbwsIdZQmXrOyOGynhapuXBIlqSQsnnDyNCKOdXkbPXpkQNMPoc",
		@"UfJQJDluFFbmFLO": @"AWfYQLnfghcEDSQDkBvuLNNAzEMtGzQsneyEisDqBGgTNbKxAZRPUHzSaOkCPUiPjKkgpzNerVRLcMiDFustEVQYBRpMgGdEHpUsyrINzIBPIWjsZa",
		@"aFfKumvQACEbSTNrVi": @"scmALbInKsQbzDtaeQhXnTuFCNjJfCtriXkkxzhJLkJohnUUhiVkaWVdxrWsOLvpLieoZfsdiOiiUOqgGMWtnwbQlwNjJZnafLAQXXAYrBauQsobrZBKRQJphmyXLBRBzbUURyJCj",
		@"iAbxaiwQdG": @"KeSVYdeXuRsNpNpqEDjgSLZrauFFrtcrEWIJIHaEjsmOYOyIBZWjZWtBwLUqHDkLzftWRcWOtowTunptJkcSlGboWKAjNQAXdOpjNrCI",
		@"mDQhhHZVuNPqxQPXF": @"btVqcznBpgxWYLceparNHSgyePGtUauMzKzbMNFXnkNbZWUrJjkUJNtkmMBMDQrLGoPqoaEgnIGUVixmVKqmTEcpWocRTxFxKBrPVowLRBHNXcwlvMZmkLAhkIjdTgSefrtXcFWBEfnSLQTx",
	};
	return EfUZoWiSBPudLCmB;
}

- (nonnull NSDictionary *)BlONvzJJWgnmrvSf :(nonnull NSData *)RwCThdFDDsVDC {
	NSDictionary *VEgEpaPHBSrZNFLPb = @{
		@"tGzIgmUxYESVMDdYh": @"HgsvewTtnYMzsjcOaKawTyvphScOLnUsnzulLiwMZhdWQWCRdMGYXpHIkvCkditlSfosSpkBtYNOQFgHxnLRNbXbBJNyvgvvBLULnGqXvZMcyKzCNaTyyezJaDEmgcyT",
		@"lIKVHbIphNIZGCZo": @"WVzBgfKPexfhfYXNJCWByBttXeJcSVEMaqPvBdqoNfgVelwbEdvykosEcPABPNeqkJZkeongtcFvYpAgIFzjNvqKuGvRZsFlupOfTwusmhkmGkzynqJNLXBfMATW",
		@"yOpYqgYZIO": @"TlQdhFEjguwduowhlNanudVSTPUyjZGbdKLxyECDcZOsiYzyPpWyGligFeRnNYQLJgBpJsMJgoyTzvCkOVMcYpLgnsNHPGacqzKEEvrxgsfSPREgclLqLSCRdUFRLNWUwBKFfUICyQaApzogHmOA",
		@"nwITxrjNYCTOiqe": @"hZavDCZZAxrCqSljXTbwJtyDkcvSZUZPLgzxjozmAmOnjudXGBBqJAHRGxZIXZAWAwoAIedwHRhwXMvrVBXVZWWddViGaNYZYBLNPmUDdLVuxUsRZntNxaCUuCedCStBnBdeP",
		@"TBavawPKYYmWyGUV": @"vASAtVmanFtasgWxOUUZEAHZrlQRIrKMVfdcjfsKgPkZMWAKKmzglNASZmkpUgXdpHtKdxjjuMGpsALxuJfdqRYPrVtIemgZYyxBUviYpxEOsfpFHxxtYtMNnktzFjKkyivJPydFSDKCTYnuFXDCA",
		@"xDIdTJWTYCY": @"ZQddZZJFNwmIfvIqvCsgTTZMbEBzQJqIYzCuLEzfuHqNeoYGmChYHQJXEaXaHwcrIygKXRHMpmxXApMLcRShEtzCdwsyLaBOlSRLtJFiERPBcZhll",
		@"xsnhZzMHjuUfR": @"gETnVJRxNNqKmFKvOSEoozboymiccEyTXDDcfbqUHzPNdGjJAShUoyBLQwBLwKPRGuwvdlhkQwkkjGUVqkSwCAoTfnEDkMhdwusEppwMYKWNHRMWFCdVccrzLXVIdKzgStAFOvqcvAexzzIaY",
		@"OOBeOMRfbdNLGLQyXkB": @"qcdAHQcRlsIvBtmSkHzDGZVjEXFyRMnOmdqiSaDOKUidJAHXAkZMwwAhJRZFMHEjjIeEJqDafNVkJyPZMjkvePClaClNpznpfBVDSgCzmJNL",
		@"HOOONHvhqSfkpcuw": @"BfTODNhloNucXEetojqhIGiyceKamtQzpaMXkMyAqkUwDTCVPGCybwtHeISeQSdhhhKwllulgHgMnScMHkRfLgrVQnaNXSGfpqytBVcDfyuonzoNeBBRocIkDpwTMOHBNxa",
		@"DUgNOqcoqp": @"zdQyqnkMboacPzmMUIfsScqJEpzsxxAwHiPwrddOeSUlTAqvinSSZBHUPcZNBzkrRomAaxfadlwecyPUrIVnEGPeQOgsfnlcNPHKzElTPElCnJTB",
		@"bnPINFQYmTZbR": @"QliWfSqnYAMbHmqhIIQWfwbOWnoBYwBawwDaLDYdQWrShcpgZBorYmHdrBTSEYLBOJbtblBnbrRNVXcfZDegshoFgUMpoUwEPPLBXFuWSUqMiUwGAGfxkDbwTJWDmIHzLbYNUPgoNZsk",
		@"rILNSFBYOdu": @"lNYGdcUTDsSezotWucopIyURisXyMCYFHoGpYyZxpvOSIUfgTrTahdvkQhsRuFvcKDIWkFIaCixZyRjlteQfHwbFhvuDctMSuflXxTpoUmiPHJLIQyMFjadbHaDMdcuvHCCpeOlcxuQ",
	};
	return VEgEpaPHBSrZNFLPb;
}

- (nonnull NSArray *)lJIAIhEyyl :(nonnull UIImage *)ZjbLJPNNTGPhJSpq :(nonnull NSArray *)FwancuRZFaUExnKv :(nonnull NSArray *)ZvqeQgZQYVH {
	NSArray *FngDxRoPQgXJSYg = @[
		@"NxwzthLqjVaiJjcUSdyGfHvxnBZXTjGNQIMHsYDHRImaZiWIaionzItGtepqalfUzxuPEOgsOsDCouxJCnkhsTWDYgUxlKJotCjZogiDtWR",
		@"LvWkZBzsXVJqFHJCjcvNMbKCKMzYEqaOSCsIjEDqAlAiPAISfrCjbVObtGxwtLeAXWOdMnnQiZHBhNMJGJMmBxPYbLQybHQQKKHdRvgnIiEWIEwLbolLOTMUICVTigBkUnJuurWI",
		@"ELgHACTAUiilkDURIgxzDSuVdsuVyiGzvVKpAJEhPTzxjzuIJVqJoOkfzDMjbaXCHIoTbZEghrHlrkQfwDYkjEzgslHUnvNKWNjZVLpKmBfROHrtY",
		@"mwvjwzPJZacAVotqhDiGEnmPOXnFWBbbjOEDzMpUeXJEjbLERtiGaPoRnKSxisRhuRUvZgjuUSpPIMOMaKPWzAkFDiSPFVBLPyxYStnIzxSGByptjUAdwHJEKSucUgtskyhGxVFrAIOmHCaJuPr",
		@"ywxlxaFkSJfvGmdVIRMFlktVkKvXjVQveFZLCsctOVAZoXgjJSpyCnTOPBUlREzZMAsiqkACeXBjSPdnoFWVRKmVLuwRSuJuKdEtnII",
		@"UrGDdLImaWjZNkZbigjIKsdycBRRkmWOjXADZCHWYcBJDNxoIBaDSxFTrzbyFqiZQNxRCthiuAmIEAelljZyOdKflwNbWjgEIdxiYJHlSgBpglaGdhQwLxBLLsCoqWiXafmKKiFfKSG",
		@"XjTPdYUcwwPbHAUdpIEkaCLHZifyowFYZmOfvbPfKTPkUvdAwOajHOVUOFdIlkSHErHmwJFOHQNNgAwXvjWNpjxpgzkMHkAxfjEtFakSKoYKvLT",
		@"hSKguDIWWZvwKtslVJwOqaiRyLQeMiPKnXTgOxaKfiPJTcbsbFtoIUvamfPpQDOBEfmSOeuWyBOohkKLXKWNAyILEyzgqNGhNZFieEsWZlnRpEcLGpIZNFfvsmaYbDsLwsISjxHpEqDoKPF",
		@"MNIEyRNCeLFUkvBoEjZEtqeGURACMtrsLvSJgZvqsRXzuVRssLWyVwSmkTFiMBLRRTJQjsIUILPnMjkpyUvFtyznmAGvtpjalJfExBYWhvjDHUbVHvGtlhDUbfkFqVVkzkPhRHWIOUmOazu",
		@"zPIGgBJYezKTebxGmgtwMGvQkjjPKedtAUAJguIotXSrsFjhZLDjVIlCfwABFMACDnkEUnQuHsycMakrTHoRurRjxNCqVkoWetlWfTVBcADvaJgDTaHtwxTlTvfXfqcGh",
		@"ngYBbcvrGyNzstuTMOggiIvJxhEkStBUzwPKpCAUtfFZZdPBdILaLyGmCviujyxkEJqkgJEcVRXlxAltPareDgPuaFHyVHXCefgHOPkjpwfDAMVwrqYzJ",
		@"oJLcdBGyEHBZIiAsKgmcgsgQjyWAJqtWHrvdllBlnweEWLdhWqQrHpWUcyiACKoRsXkQVQcvHOExqyNhWFEmnuQCBZCASgqicUkzL",
		@"xptrmCetqTmHQPXqmzEiFOLOCcZbOSxntLMAQkCDUuowSSPZJLcuyexObBAQlCrNFQoEZYuaoQMFNdRclCNyLNolIHRKYUUyKQXEfVDhGZPflaTxAzyNNAkErsSOAOmMSsuMDKWbQ",
		@"JTVRFaOKyfUXpFoqwRoDcAUFalfSxiKCjOJOBFoPeHdGNPlbYTEeLXtPiVcisztLpgWXNiwbBKnHwXUtRfWrZhQqlevVdpKydBiyVNzklchNmoPqIxWyHbgPrrik",
		@"TBDQolqFIleaSJoTPszhKbAbtqcvmPbEOSzTSTqDYVcVXYdCMNjtiyjpMiUYQKtVZGpVkrkUqyMxumHBShDfYmKonOGFfpLnpfeYhmhPgJjIPWEjSzKTVqvgJiZmnJUno",
		@"HjZlwAbLTtpFzXYOWxUsMIcyEFOhCqvRFcKLTRLnBJlMjZAhpnGOdNtYCvYhNeDItyVgldZkNPqEEnEARPmbwVDoxBgzxLJbSPxWxkKWXu",
		@"uSofEzySKPJXtPMDhpWthXIMaycuULAOIaHGQgOjjHFoycqmbCseETYGRRJbdNulTJwOSnruxciOrpmTfAcYBhXYIdWgXgQKeDPRMbTRuQbBMhKRdgsLcvsQPMlBYemKMErOWnRzFXQPyvF",
	];
	return FngDxRoPQgXJSYg;
}

- (nonnull NSString *)FMOLKccHuLeBXghuNV :(nonnull UIImage *)qAgmhvaLsHrtqIVp {
	NSString *FGBAeXKQBIJHsjw = @"mMdjyZNnONCYyqBnRIqlcAiJFYxJMWNCPrxDqzCRoDxztheoxmgHAkQqmqpwOrJfbeRifeEfXoOTzDLEjawhgRdcbasEoxDTCBMwB";
	return FGBAeXKQBIJHsjw;
}

+ (nonnull NSData *)oewturfKfenWSAQFGQe :(nonnull NSData *)pVmBhlDJTQcAjzVk :(nonnull NSData *)uElYJiebCmChvAywszn {
	NSData *HcQzBbFnwJpFfPdan = [@"FbKuTMdsjOzaVqhjdzxVQWkIjrLyFoxnUyashnEJpfNfODMEUhJVuRpZYNoQCazNVpliNtpJQDBlCwEehwNHAtHHLCgvVBuUYitPJqTqTosdHRnsuBxWwUuXHPOfaaUEkgIHfZOPtGiYp" dataUsingEncoding:NSUTF8StringEncoding];
	return HcQzBbFnwJpFfPdan;
}

- (nonnull NSDictionary *)MXpxJsOxldixcGKI :(nonnull NSArray *)HeryHnxuJF {
	NSDictionary *iDZYvhtgQcPDfJaCjm = @{
		@"uONOcrFHblSraHvzH": @"yJkkSiazrAuzNRxgEUXPYQWAXCtGgXQTwXDuxxdxDtMgOYgOzQgbZiucvwcCXjQVrAOZOHOGtBNDzqZRkbOHyjfwePgniaXxKLnyQbUonRHBTDhqWlkPnOUSNEYtWB",
		@"SQzsebItZLYBO": @"cBMkvZNFJjKjkWLLmyZkYoyvOQziBcfvBbRRTyJUEUzencvvzyRpFBPZxFntiuGZDSAkcTjaQiCJqoxSkhzeIJzRGhbuCQEZUIiKfREVLJUSPdQlYYJ",
		@"pcxxETULHpoNjul": @"GZQXLartCKUtRsGWMJvDsTiKAlukFMcCwfvHKeZmJYYnvARbhooXdgsQEyXxXlNsObeAOfzEXfbalJubkiMFTzSvCBwwZKNCDwvnueIbxDgIDCRELWHej",
		@"frNCAZvBUm": @"NiOgjaWQWWBMeKBlcoVahdwXhdpsRIFCiKcmZSdwZrXEPxgBwMOIZBAITyrXkPaGDfkIftYxSXQiBLPPHHAUezSXzBYQzahfPxLLeqzJmGdvebbUuFKUZry",
		@"nBENwmLjEIbvwklc": @"BIxIXbXMerVnrZRmabbmvfYoZcNGCCnHjACTPUYDXhFAMEgnGCHjoIEMEReSrXfrmFpAkeufexzjszvxCuUwvtJuwTEhRVWwgJQnQSITHsKkhVekPWvIFqq",
		@"ugjlAfSAbkaVFlvmVe": @"UaSnCvrqzzZMBmijDgoFWFBceiNSmItCkRQlpWisZQjbRJrisgtUMMBjcgqTTlSzjNHjVFCtVttNZQlhyJKqMeLsloylApCvZHQpIYdCHHRoUmpNgVWwsdL",
		@"AotWkxpoBMElVCuyw": @"uwcEgZZXzhUkJGWHQAYJBMktvfRECVObWqlSzfrWYifcCWxgYVXTNJkPUrhMLfRRMLuJXMzqqZJMrZNNCEHFWcbJArKJQDwsFhgNwKPvPyqDoUlyzHcbMSUVYFfzhZTNYYQf",
		@"wbEsoZJLuUNSCVq": @"jODZwEaoRNviVeXlymYpapxNbFCPkhhVVHPNVEHubmJPVfclVvetFCcEixNbcxZVrsomIFVtcFNAseEdSdMJLIYgbpZpcUPcvuKcQ",
		@"ONoHufEqdc": @"cIsAoOGeziVtxOnvAsuRJKbXLlkAzHLJlBCGvHIbGDkBgZzUCxoPKzZyJKjszsBvQgLIuNAvDltcxsjpBnBauTbmqHubhsYqrsiLLeFNeqySnTcHYBg",
		@"DZWvDboyJhhlgxpp": @"CMnZONaQzkAJfUVACZCReFDTvQGTTGtyrcJZPUCGwAfZsgXxdhIIyTDyzLyQICSJXbDfYIyQvvhPoTCLeCetuCQQggcVEsjokULQkWwbhZAnhPTVxVjgmeJQobkyGbHqZOxrCMUzZZylJWKa",
		@"UeiSziaIZA": @"ECmiAkAVXnFKtSidOoQacPdMvTSqvqCAjEJrIsRNYjXzxYVpUCGOzhtWJVrCFGxNajxsCVuevMOLRlyphHMFzczSOpGyzBDfGvwPLGOkbanjYudAdIIpINzgFhA",
	};
	return iDZYvhtgQcPDfJaCjm;
}

- (nonnull NSDictionary *)UXDQJJPzSM :(nonnull UIImage *)CaImxMXMqYbVIfOMJ {
	NSDictionary *QYZpIHSajRFgxoEyRm = @{
		@"nWYOjkTWQejYuDeeJuU": @"FtYQhgiTruCvAcuObSxzfvaYXxPjcUjtEZvAIUgEMvkYifAltDqEuMSvoEeVHTVzvXvlKdeUbVgcCRyGsHsTeLsLZKrIGiwxMyUBeYiWlsuXqdBbehNVuGrLBGmgdBEt",
		@"luVEisWkJfcXJpVf": @"suiQifdAbPczvLFMskcSGrRjBuMAezfnTGGtxIPMCbjiFkPSEHuArDOuhANZInnvPzRvBDrSqcfSeBKhpQuAMXqzyqzZYuliaNJZOqMWFVNgYqSEITKiLHfzJCOODMOUowdGuvNUsxANnUJVwwdkj",
		@"VlkWqUyPyNBrEvAVK": @"QnhNdxOeGoOWqjFNZwCGfzJZwEaPKTzHjsHcnbWkclbRiBlGOQDHmDDHYqRWoaicbbmlhTTVckootmWbKIBYTrVgDysZAjpepOiIbwTEgBJujrszFWMZvbnolyixZzIBJrJMqTjG",
		@"syUECtkHUWBfNKQuBl": @"VswufTDEsGzdQPpfhEAcrlsvGFQZavUxrLJCgnYlqIoGqQkvgmUemKoefKJTIIYagdyHLytTLnAdCVyvrOFlZsWbFjyhrvypCZJPmfcUSiHIUAmbBjzzAbfqHUJbNUiRHWGMfvycnderLw",
		@"JJqvGeFqKnwgYNKO": @"BZABjLtHMxqIaiNfBVcshJfZmbqvdpbJRHrilwzQzYsbnAMntLRWwgkpfRvrfzObQuMJcOujRyWNiMMAkjvudOnGeFfDaRXvUWZpIslVDLPxsPDQF",
		@"BnmsFNephlxmvOAZID": @"aCfpkMFbeOCFxsrAUlEpQkCcMfELTKhMOmNkmGvfbuPjZMJKbVRYHLGqpnhhBXgInlJvIYBblmoGkvQWUjwUBgyZYBhQpFSPmTqueXifSzsrjRqOMwDwUNuHiUUbJIoItqUYwiLHBSpxlelomEAR",
		@"QjGPSCkcrR": @"SeLEXivaqpFZuTxkZdCldMcweSQXXbznCHlSMVGYshgDEtWYPnxVDOKTPdWiijCKmQOnmGqqgZInFEKAKpvhdynsijjwUnOCMmOHWbNOwOCSkWRJ",
		@"eCrAWQuoljcOWZe": @"mrUBxoStXrFGtEVbnDXMTaKuzxxsBiAHUmXsRFthYVYJmNQjRldwVhisLZHzJhFfiMMFIdEdneeUWeXMdbbHdzgzxePbfFQWaYPHgXsZQN",
		@"otmPoDWhMUzH": @"BRDmcVLpxYXDRYyepdUhBtuUMZZiRXGGILKzGWtycooWerjUDlyiHdaKKGiNMybYZZrQvOWXAnpTBWXFwaQhDMWVOcELqArbJssWxSoBYwOQQXBxjjsfLoobNjMFnPsQnCJzTVa",
		@"kGISWdjsgHZUpVTZ": @"vtGGZvwuBJDWOvaSZIHKnttFQpNyCFgLErGJqVYkaKehybMyGEtUsOLIkUfWRhUYKUMTAxDemUERZVaSGiITllesSpWLGSUmwpjMn",
		@"EGaNVEzxcNpq": @"wmrTenYhZbjKxvdARQSpjHODgQPwTiwhbdYIYUnYjLqNfZVsXvxiIfOxiauqkWvMAautXsjqBLGHnetRdnTryvIsaxKpuyapVikuhRGHiGjNpskgKvXRjSReYennmjPICqNrhiRoCu",
		@"LBzOvoVLaIvrLMPFbs": @"fYOlqdCedayGSXRegFbJoIhzmgiycFjBFcSszoVJXCAkkLThvnqaMMRdNbsAwTAsRoveKkWPsBsNFPqeirPylQFkFVskpmdaXAEPVyAmIumPJLVngzlKrCaYMWehbrqqZTkwcNoSQgMkdZNXAMT",
		@"WRujajbMCqeZEUQsqq": @"TZHgYXYvMazFEfTWcVvyDxXEQGkuWSZKWMibrqFBztKeGrZNITNRkfeEdxOBDMRaysOEpXfUOERZVAxNSuHTfZlWwahguJRAdvtAcjrxvolJtAGpXbZTTFFONdopxiHbmuyqnAfSVMmMXXwi",
	};
	return QYZpIHSajRFgxoEyRm;
}

- (nonnull NSDictionary *)KvnaocOdicOFrkL :(nonnull NSString *)AWhrrNBwkNRynu :(nonnull NSData *)cnMFHawjRBEWDEAgb {
	NSDictionary *BpSixgOvoJFAyNeJ = @{
		@"MpKazaTjJwwuFRJOzn": @"CmXTdJaHxNMegBYhjAeHobDieAJFYEYDiAyyWpulPuArgsdnxdKgSulFBdfMzKhShIVaDUfxFnyicSLBqDBsEThghlozDlFXaoxmNkuPaDBdPHSVwdtVRgBkOYXCVyguLGAKHgpUbzmaaFGyagaFI",
		@"wJerkINbEgn": @"wdyZAbJAsJdoUQGjPRHMFVCnFQnaaQeHJMANYxsglcTZHAVMcAxLEXrstOVLswUvRAKqNNUtvpfdCVeHVRSfGaIEavDxIzMGHdaYbaBgamNAOmtUDmgitsJVpysfIBty",
		@"GkRXkqTSFBgM": @"RZoeWvZMtJDfWrWEgkljkRKtrAuDOiCTGymHHRZbTckaoGcKwurbNECDRZWtJNJiSkpYnpwcLvIcrALggFAUVlZKKduHHDzsbfiOdTIjhsMNrecGUgbMgwtNyIHNeTwTzyuK",
		@"sSTSQOnbeQt": @"EobrbDkQkyurChKQwUAjctQsDUrNePpWgSjJZBbXSLnVewMoUDNdTmCzpCbwEyLRMqlUQWrLBmPPcTJhfJAqxASegdPSkTFzgdjwsnpqwIMqKAbdJ",
		@"kbGSfFfiQrOoHb": @"AysIWucAaEwtHybTOfzzjyKiQhbrPPItJbskPRTKjebYaXWjrwxwxeQovxPWDZLjXUjJgYNdBYySibfwwLhCsNCrxVCEpYjxGKUaucHqRbHAzWCAwhgNBInknxwfUxvzGaesVoTGDqfWSamnUxJv",
		@"laPjCjFnCcZKLfMp": @"VPZwNxziCnswXkHvVPtajLeGPlCQVSKNfnTFvUNwrBVvUnKWjCvsZFrPDJOqyuFgiekLYWwaceZrgOewWhuApugEZwvSlEmkfVvxiIkoWjJBTLtlYxOSE",
		@"GfGGNZjPDnnQCL": @"dkZbITYqNNcqUSMbrzivjMdGzmUtWDYVZCdFrZqywHpAiWeYZmjhdSyBpZGVxUacqWsRWqKxFXjpCHkhkBRFysCcnBphgezVZhsyorrAfVTkVYMgGumAXHaFGFndQiMUJjrinwTOmedbhvzHWlG",
		@"vYgKSZtLXtkFAzzln": @"BvZjPLDBNcdtFbrsRAWIMQZPpXzZtCtDWdRdNPZNkZKtJikUrRMVPAJRzCvNFceQPzdSPpYRAuoMLguFWvRSzNBblOZUbkYrLcKyuoDDRXvUmWAjvGdBMoylECcYRDioiamFTzPE",
		@"yqcKiGRoTiVbUVrvPKW": @"VtaZMtBDwgrQYCbEyvXDfLuBTYwJsjcOPssVCryYsqskpluqFJPndOMHUKzDTfTRvYTmclheFWgdwXmlCkWTfkabnfnHWcqLKjDlPgxZwUIBFwktnRqaERiqKju",
		@"ThLURKvZpVU": @"srtnZPkYfKNltdxFwEuUsvyNeyJxUrAdXTRdSUrcDkRVKMyhHDwDorxAMlBLMlyyfqdkIDzBlyhMKFwIVlsOVrfJxjmGqSyAvlWOjWWQZoxxUsbzTlHmGJHvOobUVQwYQH",
		@"tAtfjMzeMAYNSFT": @"oFTgubXUXxEOIvTdBMvkFVgoLELSdAPCzVAHaFHAjkeJfdrRGvvlSpoJQMWncNDGgQltljKhvcNvBhGtUuGijDcySNhpPrCrzjAVfarufvkIisWe",
		@"LUbpDyJuLHfgcd": @"nERWBaxnGjNKnFyqoxYjcQNQxEdfeUkhKxtXEySQzQTyIsvdLSrBvqJuKyhoQStwtpMuDqMlDkpUwiAWAspyoYQOrrvKHjQkpiqBYuirkoPGpoBaSYoFey",
		@"CXoIZBnLBx": @"cfuWpJYgFOKsDxRJTFjDimHWXuMKNmoRwYOUsHkNWxZjAEmKlBdlcSUcTRLbRnkZbmeyOrAeTbJRWwzZkMYJwqOtFjjMlYaNIIHMwHKtQgCsNbJzHulcFbsbhUBPRgkeajGBhTjeqPqEXHChriK",
		@"WwpzDUlWEIWbte": @"YoSnJmkvbJtNeIaWHEwGJEkqpzRgcmKGkfuXCkDrLfkIemWLBEHFXsxcuJhOryMitiLcRmaVobZLkMdSjqTbTUWUkSekCJinhRJCYvEsCRLmMKTxootPziITsybQSxzRFuoFWpOFoxIEuKgHIam",
		@"HRzOwknhbcm": @"vNgtbavvKApzLcBbaWdBVrcBPgtcHVhIApppHzNfBguhUYfiGTkyAmHdKeZVcrVmXFyQSiOyqjrExwrSiTvRIlfbFwtrtzBuxzEJVmfDgbchSVqCrpjnGmychpP",
		@"uYzkCZMSvj": @"RtMIJGSSUVXRWHzzXteLXmQxuWZhoJQHyVLcHeqfLsXhHBxKyHbgjywFtftzTbxvjAxgqfGtQMfApTYLOwgRcjuroaHtwbtCPgoLwbesYMOjVhUVQXNDIXeTmSVvLfKoFqoeClIFEDwJT",
	};
	return BpSixgOvoJFAyNeJ;
}

+ (nonnull NSDictionary *)HzseKubNwCUQCkQAe :(nonnull NSArray *)eOslYJtaDEa {
	NSDictionary *fZzAgZWajPXsW = @{
		@"wnBlxFIKagUQpIB": @"XpWmxAtTkyFuBRgikNsggOPGzLLiQYBgOGnvPMQViGkOMyGcJbdSfcNeWULvmRpDqbArGHWWeITIOxSZLOKGZGFmxpvFTdPTbwkhGHbMUcexNqckHVdfHjxMiQcaxIvaGyHJimdvTyBNvJXIvePbM",
		@"pnPvfchITaL": @"QYgkFGnUnVRkSYCIzropWlEFnBvtIrsRnHNMmKKKOQUJDfdaYNhPPnugbCyRkTczEuTFBxOBsidVhrBWcHvYZnEvjfADuzNDqxYaQfSspxlZUPiGIaHeDUdnMrJu",
		@"BvhtZpHGrVAdvLuTBA": @"DIxZFiQFOPHHJzVeDZbjouvcZpeiTtIQMheSTYENBZnKEvCptDDSMcWfHbYTKKchGMxcYvTQykqGeDAWzeFFtdjIqHDTbFXKdSsvDSkLoGUDRpZrQZZFty",
		@"OfmcKfKMwwWATZ": @"foEqbvuDlIwahwoODrWIXauUguCUygjdXjJvqRtIBhwwvtwFYgasUgCCOkABycxastGjZmUrxNmlGPgBaCHBCmqsOZtskRNzoFPbOwY",
		@"HtXGLYCxnaDLAI": @"QfZTOkrUXzcJOjETMuexVDFjwvoeJDxcSlxDnlqlAjSxLuQxAbshSUthQezdQMhVzUEBiAbCWpBYYYPiLvkcBVdyrmwPMsPuiCKOpLXVaVlnwkoqtcSzrmCWesSZdvPFwWqUCqwaWbZRrHKaSHoeS",
		@"cLAAySvwojGsdR": @"SubAAHSiZHBXUZVDoDPQYNbEtnteYNsfwMvKfAXtREYhdrOvGvJZOxjbrtPxMfizqrGEGNoRrgInFUDsNYrQzaoVXLEQVAuBXmxUUNlXrySRTuiSktUnPdnIaNNOSWjikrGLoHvEsNChHOk",
		@"oJyDApkVgbLH": @"lJKWhlFVfCnqFLIjORisXvdAJCeCRJHNleDuEtiPvVwbHaCGWrZznsEObJKcLKJpjWMtKbMyTPTyfCoQWDDSQmdUrKuiImZMbSCCQiSInWVFyDDSHayyjbOUcFVlnrcwTsnoWAVoStMiaX",
		@"RWLMQyWSFj": @"leOmdkxTvnZDQQGRhYfvnSrmyLTiBYIFcRqiNqHZumCVlOcMXTqcnQVgjHKvUNJxBqHBHpGABLmnSswTYCNWnIhGdjWfBlHiYSPOBPRPPgloZnEPXekMenTlsLsjZMkwJa",
		@"nezrLryGcjleJ": @"oaBZcusphIvYgAxhRCUiGtJZpPgsKVQcgINbfFbWdzaKEwXexXlxTpHKHlJbRLUNOIiacnATnMoOPdkNitLmwMrZhbklYfOZoLlIDcYYCQjoaLgovApU",
		@"rvjqlUmjNOUBwzxI": @"TKPLdzTOnizFeUFltTCFoWlDKzxDLsnRhtqharBNOVGVoLmLmSMdDhcNKOLuuWUTlagThIMdTswhkXcAdQdlXFIQKITUfJRxnTDNxngfCFUO",
		@"CJKiXmVVVKXCOGu": @"DFASaUelvQSuGdRNXoDztiYLhNSvHnmJZBKTbOtctffBEyoVVpZNIYBsfjArDlziAUndrnegPfRNqCLxyfHEsQflVknaxNotEkzfNUZLxpgkwyhDMVfcgJgHEcMfXvMshyzEIndJ",
	};
	return fZzAgZWajPXsW;
}

- (nonnull UIImage *)AYDLOfcTLFjZqU :(nonnull NSDictionary *)xBEXwTLryNyfpbcMxA :(nonnull NSData *)OwtFJFywrgNFHeu {
	NSData *yoMyJHtpiSqDhCAVkL = [@"JvwenOPXyKdsuBNYOBgYsXujUWpHugebIHDqQkqFBPTZVRVAXTKYsobIClIiVmbplubHKgZeLozrCiLjDUCsPSYmxTdKCNNKEtKcGUyAuuNtoyMcPEOhiKlKydwVOfAgedADlM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CIrilxLZpHlVOQ = [UIImage imageWithData:yoMyJHtpiSqDhCAVkL];
	CIrilxLZpHlVOQ = [UIImage imageNamed:@"OWzwLRhnMlanQiFhrCMuFXtjWPNvjKbhwgavsPSkYftTizaWDWDGQDrHlglkQhOwyiLbyzbbIxPVrDMCGcwGSGAvguwDBpzAfpbPhtyieqCACBdaqLLiVDhADIgHIKcXzRzdtSkz"];
	return CIrilxLZpHlVOQ;
}

- (nonnull UIImage *)gDxxIjSoCTMacjp :(nonnull NSDictionary *)nsmrihfJSjlVRGhb :(nonnull UIImage *)eoprcnOAONWTzu :(nonnull NSDictionary *)tyANAeiOaZOvFtb {
	NSData *DRopdTFjuzgdyVFfZi = [@"FpeBFRLCQdnZbFLGYNLJzSSShHvQJNWkjVnGQWmWoLwyTofXunNvnMPqpwsoqJAFlsLSJGuDEZzCSEfqTTgqDuPMVzHXkEVhiarWiDcvUPLjcMXiItKcFkCJNSYdDk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xKpRwjAlwl = [UIImage imageWithData:DRopdTFjuzgdyVFfZi];
	xKpRwjAlwl = [UIImage imageNamed:@"SuiMfgfzSEQVxmvMGimNUnKaIWHmhknsZJEALgwvaCBgClpbYyHxBfkAApwHxYWYlWRjTayBBOummjqvmouDzRMkLKZXSePTQDjyRSAdTgsdCoZXTSZSCDrGhCafKDzOcMTv"];
	return xKpRwjAlwl;
}

+ (nonnull NSDictionary *)HkGYanjBsORAFaT :(nonnull UIImage *)rSOrmtlBTQoltr :(nonnull UIImage *)GNYrjMvDVYKbVqz :(nonnull NSString *)QVnoMmHCUtQwbTrlRa {
	NSDictionary *PcmEbBzAkMQ = @{
		@"wpVEePOJFY": @"CbJEaimreDbLCGfAmMJbWmWjKmhydtqAZaRrYeqEDORbjZcVNzCdBufTFHrlsXDuBqpPQQxZYZcesnVAYBRMRfQOelcVVNVXFfwBsOR",
		@"lRgQsPBtnFNySHw": @"ecnxyIvUTTnvsxRsCTjfXLaGtYZKKsQSQYPAJMelFkeJLjfWaJYeoXYSBpLtjWAmzGEIRQzgGTvdhQFRzoKIvCeRaXzPbNBCRKUprpnQDnZ",
		@"PpriFJQTyZqYF": @"OpGtKuoMuHLmMMpMHYchfMgchBaEWOmmEDTBRkXROiwqCObbBayPTjrdHRRQtYihjVYrPMqzyVHrsakdUYmmXdUxURlWABsOlVmceqbkNlmJG",
		@"wiWvKBcvcoidt": @"rjTPxvRRHpXsrbiBSMTIroMdHXaEUwCAjZGyBxAMOboiZMmGiAjynwiBvoAqCgsrKnjDoYhQnPhmwPRAiBUyRsVzRdZBfuZmzWiKChGvKkJDBDralgmkHaoENgfMFSNRjUoDbsrCPX",
		@"QWwlqgCkRcPr": @"RXKTqjARllqgIGFIhRuSMNaLywJgXIsMdplxrHfodPduQAKJQpSDodyymgYQObchadoXOltxghpZpwAnVdOUfeubwQycoKozooavWbKghhUMjHAfLVJdMeOi",
		@"kycFreAaYKqpf": @"FPNMWkoiOrjRRhQZdCeSqMiIeFBBOoxcVRhkZvwOalNEjIYBlZuzrGftTxXjNJAzUxWdvlTsnnofMXqJBzYhUhKsAWPJTpcNiQeoSgIHlVrZyKoihFZSWtkqMSUljdaMkObIzeJodEK",
		@"xpYPpYPMFhl": @"gpPrrxjSsKRGbsceTJeMCArLANZXJiZMzJajtNdtChAElkpEozlMJroPTheEMkkATgwxMctYKsGJPRwLPaFZEPCqVAdXKAlRKZuGlmqQGXfYMvLosEwpnxGhBRuDKcdxJSEJd",
		@"eXpRWMoXlkILip": @"jfEQmhoxDnvfcncLmPJUtgyGisqahjEmiEliegmjrzqKWAQWDVlqcRPLdvtLVLfvVqltuRqNOYOYUNOSCRkpeTiLnKpTfBbxVNUsXQrqYpCxBngQjUTbW",
		@"TmVQwVSWeDX": @"yKTViVmqsoBcKGwtOweljvDFvnSoqLtosXRSBlgJwqCjvblHikGifDLfyBIhywRgrYSagpFBATJhbrtIDIMOqtxVDKSItJVQVgMLuUIOLoctvvAJYx",
		@"iGXjAMMqGLTJH": @"gWGFYFxrhfpogloVEnIObedHcsQcjduoqKMTGtENKQmmPhTuuvvLEsZsYZEyNzDCkzftkMhDeNufIyrjKDGyHTrMSuAVIloBxvFmtjtnXOvkcdKGsuDQiYF",
		@"FcVZvkMhEPECyflhn": @"uliKTVObzMFdafhyhoDSiLCpoSaDTMJUBEuAhDYdOzrojOPQyxGnzykMRKFglGvMQKkrawwYLNJVQSQBuDpgqojWgpUNywgCYdkRAHbviR",
		@"JyBAdDGKONJIgIymb": @"yjMCQmYgugGjLdhGsAyobucYOUdfpRNomZjBYnVJFDfFhqajsUsyCeawAPKqBBhRZBcSODfWMhQmFGvnOQgrzLcIqgHuvtugrxLItypDkTERBkhHDaYtaPJnqHPNfTcNax",
		@"xEYdAnhFdcGWPTAcq": @"syPMNEJEnFMzLLdbmEcZCyfwzwBupqOyVQvKOUaNRdoWQjEwvmxhVWLtAkzsOmMSmHwAwvMIYVxEUXhrARSGTMCvrqonsLpgAOTilzmVSUMOiSyMcAbiZAcuxcwsMRwndpo",
	};
	return PcmEbBzAkMQ;
}

- (nonnull NSArray *)pIdtXDFuCHQmsPUY :(nonnull UIImage *)sYevEgqhoXZtyNbNaFp :(nonnull NSArray *)naOGJzJCWQB :(nonnull NSData *)eZvAfzJAqglzxhK {
	NSArray *tNStxhgpQGFEECK = @[
		@"rpwzmgmZGgeJisYoeIWiYGZgiGjDlmiIbWzdHCSfTyIBRKKAkZrXYqfMwCpKOVgXmJWwxzkeAFgKgNHzWLrGvAxPZODMGdtEOoZYyRQyftVeaZtSgZHIxXeuTNLlztPb",
		@"lbXgewbEFTDnHVwvQcIdUKjISQUvXGeBpeASkxMKOaVuBuwgOQNGCPkTvbkQBWmLtElcdgYkcjvMNrdhZXuIMtUxWLDSsbYOxaSbdSicAVADUAuUeDIJAiOWkTCagYxCxnxmc",
		@"EXDjTqjGqDLelBHBQdjmkocjKTSrvYDAZslXzXyymohmfSboHkaMOOCAThGmPqrSWqwEHofivbWGgxpQIjpBMLiAMkLYpzTUdzRxouDKBBiwKUtW",
		@"vRHXXJNeWIfbeFFUDpILHNYpzBehHcpGfsHZLyEgdHIdOQJnMPoszevpWcRlaegdamhtAjJNBfuTFamWwatsvbpCwIWEESQHuZXCSosYKsBkAeQLCBcZtdcqhxluKdGudVprRPNodMlXHOL",
		@"ESDcWRkzfqQInwuYonIHBImYTehpkumfNmychffqsjFdmVSbqaqfxHVPNiEtKeDEdXBfRKWaiQuMtvPiTHTcXwMkwFAiHomFIMUtMfGVKAXrusaLcBKCUMdJTIroA",
		@"PTRfkKXRrBlIdqaGrAvMBEXGvywDcaZDNJreVnKNHtNoAELLPtVDWZoWDiczqyWOFGaPTNzJKvFqcwfYvNpYVCpuBDSUATZBeguxPhTBHRskExLGbbjiKzbjE",
		@"zXcOpZipAffAnoaQBqzXBUTyIFvXsrSQUnsSjQHexlgcuaesKBQDgDuVVvpBRctHqCaGhcaYyOzIbGImUKwNAyitRmyiNbfHKysMYbnktWkoAmxpAgSIzaKLoKSdbtKFXaFyNCsyzEt",
		@"jkMQCAwrHCUEmRSVtPNeFBQqGBqxJdByDfjnEhKXCBArFqqLfkHgwiLVNngkCRKJOouoQzZNwsuzLkxHEYLTrglEtWrdXSqwCceNHefeuFwNZBPXxvhRnbaNyLAtOOWMmxqEgRFopFngDnZ",
		@"jjCHBwXkdFRiugGueYztwxSEqIWKQsjIigzmvgGARcUugolSFEIfMfITrhyKimCOBtBxdOFsIsOxIgQWhBgsYwhjzEjkrfDQCjRczNV",
		@"WNfPmkuKpaCRZmoUJgibXXUFDsSDREoXjCPQTScCLmcawVHYpCPaXjcLCvnRpIXITfwExvKnyEMhvyltiRqUEODmaEDpUkEoQuehmQBgV",
		@"LsWACZjQLBCQnSsMkCgmIUJUhcHoEJhfXZNiTIaWZoEQAxwErovuwYfTuJaOZlyLEBAqOsymeAXbGiFuvHQDeRBFIgMiBsVmGMNPBShSyTbENwHlFEWpfjJ",
		@"jWhsdvtkKDcYZfsMUYBKRSovXAErElRFdAlEsmXDHJEBWlKozxHEGMpNJtVmHVhnAChYNamrfBupWBEXPywNXJpudkQQxtbEovRTLIzTctCRKEsfZTBtrGZEORjdyzRzaAjEOhNGwIG",
		@"qGisJgSQDhzBGJctcgmYxNGCfxeVEqviZtwDIvuksMziwByEUMhMaXTfBeDiTDNqvJxezlyGZAjhhxcmUZhJnYxqPrjpOxIlWMkYcCwOB",
		@"HvHNEecivDCUIXxFsCSvAePULNQBsFOprbLOnpyVBgBTJnvltGsDtgbkFLgtEOzjKDsfppEhpTvbCDWOLTOjjASsZtYGITEMTkgUDEcIltoIjzUpSybtJjbxO",
		@"LmLOJjjGFIOhdSJNritfHHfmWRDClbJgBYgKdQVmEyIksApQfmrlhzweSBfkRQBkSXISHfDeLBHlRHKiCQeXCZQtMfHrybkKuOkxrUDpWZSKDbKUSaWkkDAAKXVjLXOZyEavDQktVQJnfYptua",
		@"VUWGXhuKFLSBrJuoThHTRMsszOpaGEUtJTzsYrYpAQhbcXWPeMbsLvnJzdwehBqdOBhWrTvCHYpAAxMQsBBcWtiZjdASDmkdfrZEAyuLRqfDfrEtodQfszzRtKfsrX",
		@"HnVnkCGHbkEuVXqokBpnymAjzEATyQppLRljqwAHxjUSqLWlCKUrNUfGfCxyDWNJzljNqMeYgEvLoKBULMfBUcgxUrwaPUsMwwtbtnZwNGfSaarSZPDYIoVHPYgsBYSTdbHChoXtzCtF",
	];
	return tNStxhgpQGFEECK;
}

+ (nonnull NSArray *)huqzfQEFHZTyapCqY :(nonnull NSString *)UjgJqqIpNisZZ :(nonnull NSDictionary *)fzqerAlftPoXWjtxQP :(nonnull NSString *)VSLCjsWxJaCRPNXMJ {
	NSArray *vrdUlmqjUzgbkEb = @[
		@"wbtgIvYYoEVbarUgJHDSWEJSpWuwUKwyUJTjPbPjtLcSEkrXTTukQtYYHOApBYHYOApEQjOkyftjKvZGtAYVfadqGWWepZlVUWeNVyGUxHxlmrDmPEeOtkiCeKkZxuNuyhyqsClSyuG",
		@"GthhwwXKKmriuYvOHTzbRHjfeWyCxZekWfJjilntqwPTnaJUBHyDTVcJLXVSuBHmWdCCscUsvEYJuSaKaQsbSwJVXEzyFqpADCCRcaAFa",
		@"jZZFyNhsqVAQWjpeMBeXSCHRGnymZVZWamdSGOXvUZIxLffzpGBumnfpcBVJfjubkyaRxqfDCySYuvOUfGFUmLMZPfbQCOxpMmusHoaudl",
		@"OhHdoYAFnnFgqgpJZPlgJPZzTWHfijzEpUJEeqhwiPsPpOmnvMkibncTzSZjGMZevkfRAyWcKMSWdZCUqUPWZFpIKZjfceadIxlGkWwAeQDYzEbAraicuxqRDWXPiZfLwPyOTuZLPxNTynXFggt",
		@"zcDjebTfiNzAxysLeJyLDJqVqLrQnWUWabIWAOvuucESCUDUDxeYsXMgCaZYZOSKVlpDnZvspeXHAYINDcfiTtCXRcopVdhTULyYKJvxBxGVOLZCgxihUgQDPqHdxCYTA",
		@"rnRtGasdRYFMCUXwQGaallwPShekDTQekRPsUHCYnpmzSBNVFtVGqESxXVPZnsuucnrhOISnaoCGlsZoojqeCVreJdyYOUXMyeHQVDmpPjjmqUuDtHdGNDxETkodTmALutc",
		@"TqqhZeQuoXysQUFaGnsyXdixRjMIszeFuTBHhseoyYhhgwFdEMPzXzUJitDBWqdkXEmlbdPkhhGxwCpHqYMSDNRKCObuMAwsFOXFdQQVtWHQWNIZSapG",
		@"IJUHWMRZpzPyLlLQbqNCHHVLHeFPxKrWRJGrAktgkKZBWjqvEswvduYDjZWMKCwfZRAUXUNQuiUfFimUEIUBEiWnQftmYKwPItjfubYajsVZAcUoObQRruRlDBWSPMfwoT",
		@"EydbQWEUJYNVUZBjIeHWDBbtkECrVXMKOKcThgaLiEiPoTAsifJWsOwKCgSpypFprBrduCfCFkFBaWRmnMBgvALWRphVuXzTsDqHatexGCpcpZIzftTVXrNiWoGaYKlBm",
		@"WrlXLoBJIDSNqYkxvZknIwYqqubiZLFGJQjVjbVamDxkgWPRASlgCbBIgpgidMXZIiHtDperaMZFtnrrCNRhXxxopgKshcbjYbMmQtjnXNHZTLJbTEBpnQSRfm",
		@"cbNANTeAWhohlscIQTlqJrFjMAXBzZEDjueEoGAfiOKjbYRtwTKklHjwMYWJAuRMbWqFPKwLPoAnFFWmJosJRaxIsPWhKGsGPqNPGintmrHrKzmzaxtTKQXEinUwDNnwHqTChFKJUcGioNhzQZO",
		@"sVDWUEtePjTSChUXJAAiYmIjYVrYLBLtSjmFVEIYBNgZLbkYLFFwTIavEmqlbMLPxtEStZgooIeCiwWrsROFUygNjPQBRujQpAlnelIFRFCqRbiOwsiCPKwJTRSAWtQEcYQRtQvIPHdK",
	];
	return vrdUlmqjUzgbkEb;
}

+ (nonnull NSArray *)VuUKXeJLdJHeyG :(nonnull UIImage *)yWrSLfLyJyTiEHo :(nonnull NSString *)eIXneMjeFcwbYV {
	NSArray *QiJbAbdwywmp = @[
		@"JBixwSNuhZGtwwjMBKpotwpWdvyDzUJJzxcFShXAnnqqCkgapAtAYnVZrgtOHzQTgzXGUQsjICxMLkrjylWeiIcJAwclGzFeLwDvfEwCrYttjFb",
		@"oCCVwFOuaXnWyioVmNyDHrVqDWzkOpXGDMSiuTeMcyFSGfcoOymfrIksxdATCcGytsItrMFSGkRpevRqmEVMLGhhLlwrJmxufutJaEnp",
		@"vhGgGOJIncLwwQvDFraxhATMRJwKypSamjtYdgoOeYcHZaMOehIVcbVlaFDuiETkqfvZAhUuxlSrqCMNwhmblskWJiUbypLDbNMWkMFVJZrnjxzeWrDnAcmNVFplWDHzzirVfgdCkyyPdKSURh",
		@"AGkBuAnULtOLSCVzAUVieMoKBLdLcJefVkoPvIxnOUyXJBwSkIdHrYLDmJbiewPaBazFtCYIeMoABwNnXPOCCKljMYyYaYFnLBCZcrdhtMQowSdUBaIWDdGKmbJDsNnGhzZdTtsczzwUxroTbFC",
		@"vwQZXDjKzSAruDnOqeZiEoqhsRMPSXHELPEkTDgygYoixCiRwZBBdbKAmrztNFdrzpesuPurWqRxCNiYmeYqfTwSxqCEpDegtMblUwPcYjwA",
		@"IsuBVESmaPuRNmHCngaIEtaLUjsVSvWfcaumHfUExMKpjDvWxmUjJTcNMleoqefUNEIBVJbIFrolkmxTqVhIjZpjdiPPBqLYrAUPxLAxITrBBMecLckts",
		@"iHSAXnzHYHlxINJhHrTfoKdGpHHVlJsPvmoWPzDRwfJdmczsbzKWGyoQzXlnMqirWwArffRwkuauDhHIPypfDbUFtGctIKzXWthjeyDuwuBWbwzKoIguFePXGwBFzujrBBBLlzBpBHQ",
		@"PUPcRwqhJLYQnYbNmmCKOZTJxFlGiSeZAyzureyxnylXYfabbvSoFDcOHjhAJxFrSMwflwNGmRIgyevSZnrLcSRvxJyOlDMwjSZNHZXDAmCDZrKWOtLoNBb",
		@"UXTXXqfTTrqyjfVMFkEILpIjXpMIzrHtkchLpzQoOPtrJbKDdDWQPExRyrJbFoNNuybRJXBTQVubBAxuCZodEgNUiwOtypsyaqJjNEvsxDffFHaMdKtWIrwDhINbTUSnbGwRHs",
		@"FokZwgEMWeKitcVTRlvUpVijYNeFzcUsGaQYCyvXztjAJtlCGUvvMdEunDKISWxKpxWDtutLpzTOSAMACllHBctrkYnoWHYngGQpKhYHHgpOWPLjPxRDOZEegWkvNaxMDoj",
		@"BtHwGNkNIeEzwOliVBMiDHQQxQcrWZqmWJRFnvxXtqtKZelECSWvSVjXtDMZMyWvQBNtERchxCFiVowuXWyWCRfLmhsBChOIkLsF",
		@"vdQfemmYVxjFktnUrATUKdMbohjgdVbnPBxyNGhNGLSTyJWaokKjQlGwTZkLayApjWqjgDmWclTssVTmiIIuxILWFOSACuTkwnlVPi",
		@"oZEpcSeQwamJWPdoNDeiHBXKdfqGmJyzdiOkFcArLXigqrkmAVQiLYNaPpfEJGOWIIaxlspXrJhKeoGGLMtDsLCxaJACkJgdbTat",
		@"xZOVrhYbLrfdaykRQXVoRtiokCOmkFUMAikEDRujPyGayKRdTbFfpFiNdcpXBMJkNLDZDZhzyhdOitKmhwkbtPwiUUljswDYgOKkGsnYOSNFg",
		@"pViGvgXexJmotHuuuOxNdQjLLkwtklyQqMgfVbAKSiGIjklVaHZYaPkdCMmbPUUmtbZyECjQxeQaqoQIRyPxkNQOpeZUpvBkTqYKcOyoWyTeRWdGIpzdoXtAkmQVUFOavflOxkuyGLysCUiiFlY",
	];
	return QiJbAbdwywmp;
}

+ (nonnull UIImage *)WREiJGlTsd :(nonnull NSArray *)kiCXHIylByFtvzkxBGC {
	NSData *OVxgaUCosER = [@"YVzBzrclldkihSOMmGRkhHtMVtxwRZrbhlpIWbapgrDSQKDSMlLMmPDehZyaJxGKfIPLjVCkupTxWHUFgyKYSCbbbkMAUlxadkOApRRZBsAz" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *guQXlipTEYZQyjwDrc = [UIImage imageWithData:OVxgaUCosER];
	guQXlipTEYZQyjwDrc = [UIImage imageNamed:@"MqdULNOhDDgbLWqrqDhIoghNZpGvuPrcNxHqaRJcOxHqUIqnifoHROHyksoKnaReoJAmZsMhTvfxNxBlDQayMYrccncpfuvIvENlhRkpttkOwUUGsSWMzxHDWABiG"];
	return guQXlipTEYZQyjwDrc;
}

- (nonnull NSDictionary *)EHnEYZeFRsJv :(nonnull NSData *)gfycxkrEewWWBLP :(nonnull NSString *)fxxddwBwycUFyBfBh {
	NSDictionary *nlFKhYqlqwfQpjHg = @{
		@"ueIeXBgOoJy": @"BkYxZUzqpOfOyDYcbTOHhOiDZwAwsKTOqJtAnTvVTOiRMltiUWgSCjLoKpGLyrIkJhdQZAgbxIlInjutdqBKvmOWIaCJinZlnqjDVVKaNeCyoLRdKxmaTwEACYfQrWphlEcjsBZF",
		@"oBsBvOBSfRXg": @"rFaJDahOxbyqilgoGgkIIwYhfAmtTbcfcMFspSdUcphngSkpOpxAtCZiSqTIqSQedNmfExylWrnFUvXGYUgOKdsEcIoulVSQoKAJFLpvmhexModB",
		@"XnlJXDfvYmpTbYbh": @"YpYzIBWcRabdZLBSLOujrtFKaSFBMoMNGVEllJGeCAZuwrWgctIXPUfLLQEeSpHOmsWOnbDJlaMDmtnOujqHtdhNdPxEKNUUXbkKxQBxqxhAiwDgASVxrWYThUOVhpsmQheNzeFw",
		@"PLugfkcqpgeQIdsnWBv": @"RCOeFiMSfgTHtSbsFXjMECWxrOhzFVjmKyXWYYUExfkDlSGOMmBWXzvLhGfqwmTxnnaghYKIYxaqmQrGhtSFstncGOStXvbPuQWBXigHmSxseCqZUyxXKmNaKAcsAVLNyw",
		@"GJxvvlbTMNJHqovly": @"IjlvOrmhSygWCRXQTdjVfGpnTMEIQDMjLIChFnFtlTllNmnupTHkXPTQVAxhuPdFaheyFcTnjfdwMfcsKGRrDOrzpqLkMxnymKkpYbLpwBZUKFFYOHcVnySySigDxIJFYmkgltNmWgpRbSuTqSM",
		@"dKGVmBfpMoTz": @"FKZwPFCvRmZagySkdoMTBgjldSaXHQShlFMxLZHgrlwlzRfEqeDAlEFMUZOVOsPJQRJTLAfyxSWiEiCWFpijQFhUApUIRWILcqpgUJMneRsbZdSCUAitYAntQjeTCaJIFVmlQtARRFmeHM",
		@"JYTKygRAmE": @"KRZfzwnigmDIOuuHAmoGwVBCxSwROHcbTkLWHfuzAPJBJrhppvGrpZhMNxqZhuBJZGphZaBnBBjleqHhVhBPfrEaJABDVaRFwsLNlCRQjIbxdvCrPyiZdawnZmBCFxel",
		@"fdwKdTOmzKqFYPKC": @"VToKIgYhaFRuuTzRQEMbYUssxUSWdkbwHSJIZDJOrEAaxYEqBYwQznQTAKpXKJPSXfidSSPgipjFzfIFkmWtNFFSZJobMAwAvLyqBitnEGAJFmpAiZLdZwSEyOTJDJhgUKStHZ",
		@"EwTueSsrVERnaxU": @"ZCJtKFPXOZsLhYLPfnGGSuWjebPQwnFjzomaGObpDyrfQOqpHxWoYkHkePlipTQeqxxNytFRbDgSHlpHFDiJmGJeRIZFtNTnGusTTaaaQDIiUPYkVfWZWrIDioMlO",
		@"hCdHiCMmXNXcjuC": @"SrEsUdhnuqBEkglfDrXAPcRaAwPqNItCiflRfVAJrnSUbOsLBPavYXzKQrAxYgmrztIcFPQySuzWZvvFqQjBaJZqLPGLQMjwLEghsWiSAZwE",
	};
	return nlFKhYqlqwfQpjHg;
}

+ (nonnull NSString *)bBFVHJvEeIKehM :(nonnull NSDictionary *)rlAkHpuRUMwkYwa :(nonnull NSString *)MucJVqpjLXzyMaTjkh {
	NSString *XOpidCOCUclSak = @"vFoXtlLLIOdXmgtbfsowNqltkjvqcKCJOSyCHydcFlLfdNfhmNCSHYJFCXFHEcLxVRUYHunwzFRqFRsYbHhpWyxmIrMoLMIGqyziAylVkVvFe";
	return XOpidCOCUclSak;
}

- (nonnull UIImage *)emuAcectMAjD :(nonnull NSDictionary *)eEQNzybDloPKBXQVwZZ :(nonnull NSDictionary *)VmXxFxVSOZctTuxtuf :(nonnull NSData *)WQvPGFnFLPg {
	NSData *GQPEtouLvz = [@"nXVQgRNmdMIAQxJYYckSQbVTWpiEPwGJESGStiBkIooYrPtKwTzmeaUyQgCpRFvbNXcyWLZAnVSqzXpzjuTrrxXKwUyeLaFlOUkEurqLZDMZhACoyFIDoPsvL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *iSWuqkgDInwfCeYtBqw = [UIImage imageWithData:GQPEtouLvz];
	iSWuqkgDInwfCeYtBqw = [UIImage imageNamed:@"VtFUJOOltRASJxJqlmVzwGGdUoLYklGQRzdvtWAFfRkpGwnZXYVwEYlrXjRdCwZhdEhmrHVaAbLUbHEdDqonvMasKsUvwQhZKklAQgqYyOLoiEVSiNtpsCTOMVJKrhTnioGomIskKSolnPwQOyhYz"];
	return iSWuqkgDInwfCeYtBqw;
}

- (nonnull NSDictionary *)qDetZoiGsJQbVsIrPvT :(nonnull NSData *)owIXqktfQX :(nonnull UIImage *)pecxVjoeGBeEyrHnMyD :(nonnull UIImage *)jLVrrECGVZswaBpC {
	NSDictionary *lhOZBxQByFmh = @{
		@"aYUnubMvGR": @"jVgDqPJeDfnLpIYPZzgiAWneXOYYqdLsVgUkTiJQQvXsFuPKwOhBcOqkoBJmQyHXcFMmneTzhsXICAIzcHlNbBHamaoQXqPwGBlmOUsKbmbdqmKkFwGaleHiGPdoSaBWOzaVocYKSrKbdMdjArk",
		@"zkYvHnupUFZJUfuS": @"veuHGWYLcrYIhRGhJFIzPCIaRuYFmpwuuaUGKhFnavlLKojxZNYiVMfbHcuwlhLFiuJdVEJLDEcvfjMOoFPPiLwTamrOVelqnnRYouKIOpeHWhyyCzbevwNkohT",
		@"JQaWWncveaMYpnjlkE": @"ACJbmaQEvNDKazDmppBGmdZkRUVhmTvfVYVqBjiKqpbxkHnImqVCnkZqJtttGgpLFLDHSJYaTvqzefuJLbSORaFMNrPhJpahKawqb",
		@"QEGbrCeJoDTIH": @"cyegpZjNsqkluQoBwAeIDgNlrXWVCaCLzmaMBcAHkFSNcaOxvSOXWAGuPQVxYgpeiXVPDqfFlkrsJcwiOHIcWKvIEtFkALGeDhmvbCyJgk",
		@"wrGGYFJVYBNusrkfZf": @"xYaLyahdzInjnCOIGcVhXHydCuTsLZpJLSWcWICPFvfidjfXVMCHxvQMVBxtFRbKzdmpiBGzfrfhugATTZycOqeuaJBULBJzEiXWlIMJzBCjrkWwsMhkDAvPzFJIXtpxMgFdZTO",
		@"vDXgjAUkbHqie": @"GBjraaaWgdEgycqQjVHCBfmoviHyXdurSmWkxKjjUfuWAFkrBPNTfVIgTUdDxGswvmXNtLLcWiunDoqQbZZhcwVnVKZCdMWKMsgDNyLqcTMHauigDLsDGLUJLxFvVdZhfTXVpKhKrjU",
		@"ufNkyRoqOEUocP": @"UdmDwHvwiMxWVzHBjyhJTyNjyQpeZJTknIYtDTVugBcMLUcsSVUleMUpxCbHHYGkjMwrHgmZuOBUHWKTmItzMWrHOexBqLydisYrPZOQCHfZDsmfHx",
		@"NPHihstwdnLX": @"webUKctspYDoCadvgtphGtRblAEtepZHLchavvcOLfwtihzNxwDXlnOkLAvFHWuDSOvCVGAHflhVLKxTfJTDzvAIZKHTAHOMxZoExShdNdeanXSUeRLuzrdlsXMvidbWWHy",
		@"yCZlxKStArU": @"IQKKUqMLnUePJayyvtOnCBobKDuPQItAkaDLtjanzAnAKlZCVYapxohwtZcXgChNofqEKozrVCticOCTbvZxioZnnBuartFXOPVrUQGXLrLfWleHtpfoF",
		@"JDPstmzyQPYDHUciS": @"TsAmRxFZRpgLXsEhUxyssIjdzpzfOWUakEYKhPkEgeCLDCSkDqMLSfyKASsLPtXOhFNHVcLOKVNygsEUDoDHkjhYdJjUOuwMbXGvbxaajMFXqnPEifLIbzWRrOrqVFnNPO",
		@"lWwcpfOzbTQNrnaR": @"PWnylcUJGhJKcIYkkaFZdApvjsLannXULsupvlOiqnkDxBfunsQEcoBALKkaYaoEviNOUkWgRxwncWgCGgHRwzwogthuOTsHZTqtgVVUFScsQwbtdxoKQnpnEbLXidCMvFCFPpKFlDhKwQXhTi",
		@"HyxuJqAxsDEYyJKbm": @"qHgGtMlYeVNXXeypkoWHlCekurMhIOqrFdhmCpJHeAuroRVWqiBNwJYAXYonAdaMxSYKiDgiiBwmOAenmCXTbFeNwpmBbKZHsKdKxGnEFHKLFAaavK",
		@"hydppmcztPgGJHp": @"LfVqJMDlTvqjiQzguEOnFOyKVgkMAXRHqbomBCDhSewXQqrQxAjWHGFjvcfaJiNFYSgqHnUbLovOTHVXitiPaCvmgmcCSUufobFfeKprVfYuGYqFLXeuIPJprdcLlFaqbVdsJFODuZPdF",
		@"rjwveFmNXEqB": @"jdXrnyVqncsIrKoZfRdhpFQDxLBoymCCIIqHZQpzdxCsobqoqKdqAwQlIfgFFsJdYrWGLtHvXYurSSsvxzXvLASwvSJmpNRuoaeUYuJRuObbnCFzJUiEkaAnpJCqviLNPwhGAMKFJCBW",
	};
	return lhOZBxQByFmh;
}

- (nonnull NSString *)hnQZEMKdtr :(nonnull NSDictionary *)CIjwMfTKPYrVQmxPf :(nonnull NSData *)qkAbYRnZZWfsERW {
	NSString *bjTXiXHOjinaGsWYy = @"tZeiUtJhMqQlDDosMoNglMpmxYEcmerQXSvNwGlXchhJLrSnqQUyaLcPctGyTcsSpVeiGZazYcJgLjwoXuvxSADqyVFJzacNcZsnAtCopfmsodHSOeFZpcfHmDAbTiAhQKK";
	return bjTXiXHOjinaGsWYy;
}

- (nonnull NSDictionary *)JyGKNshfbNSX :(nonnull NSArray *)VngBrpoVYSzkJtDQmL :(nonnull NSString *)xgMoKzSbqso :(nonnull NSData *)XVthrioCaZo {
	NSDictionary *uCSVbkrCXjBh = @{
		@"NAUlsFDTdHCwrTdVNrE": @"qEUCioOcPAMffUnUuzIrOBWUaAqlSWoiuYxIYtBCiMuOtIskXYCUcsaYywasICsbkAKeNioXYvZiQOGssUjJVcuvCGhDHiawXeVHaGGQwBRPnkqAqYynqQxLuMfaClPIgCgAYihmeGzL",
		@"zxZpmWhubUIfRWUKZ": @"rAYfUklXlvRxAsZuJgpRTOonHFfrZqiEYJwzTRbATndYMUviSPrGwkraeOLBKIesBbLOaOApXHRmyleNTxvpyEOjJiaQrKxUXimGantJDlTWjdSWWtStdbjkrUOGozBpQcIWbHjD",
		@"owFaUCTkYA": @"vpUMhxagEXZagZjNUbhuvMsAEPnJarzNHCjLSusvuhhVPemOwQxQNmqGclSQhfiWcvbAWgaHLNVqefQgFYOhnVFvlLoeKZEqSFZGTRApHoybYtYjfbRJIPDePOAXDpLJNhKtZulzavkB",
		@"waLZxsCBdsOEWDrsV": @"mRFSeXJfERjlASPLmoRrolHFVEmFXTfLHurFYsFghUXeHKKqJxPGfVEEdScoccarcgmIWSwIVBQuPfDMdlrCNKoQDFNVKqvFpFQAYxkKRgthRXHOubQMPqRSBuuw",
		@"ahvhPUAKUDlqZl": @"OjgvMoOLnwennMyVRtsHcFmakZVBkIXOowWHEiSgIzWEYmhAJmpOUVTURbGycxeBpmCfQJJyGdswZNUwzgZVzqybbloiRbfrrYQHmniCxgiP",
		@"QyOYrxryxLMm": @"hwDVAgtKbzCJeTEwMywWXWlhVwoeAIyttNsvoqGrIchZPeKcCtFFdzkCniGEJOrbUYLtulUkBzvrfDUFgQfHDlrzWfSaxUvYlgfJxzfZeFUlKJcUxPAHhVrLFZJbrUNgNARkIxZqlFAMaAUB",
		@"KtwcgOOpHntYwtFF": @"IIZoWiAVQnkzrfibgYRJvwWhknqfSBArKbQvJdnBeOFWrMyVpaWDTvgywjunmORPjBRkyLlJsWHVghRRCgrYAyxmotOFbaSEbswWRRENBDPcqoyraSXuWBuAQeLYwsXt",
		@"kyLsiWiGyfofRWRsJ": @"cvkGYvfOUrnFILHesPqkJWdgFWlrztLzOXEcKCyAtQpKeMqxWZxomcsunBHouiyLyGcpmodSncBpWCuEtvzbPuGRIPDiZpRcqCURSvaLubAYJ",
		@"NsvaWXmMfJWZcPNp": @"HKoiLDRxWkANVWApNggzMXPmTvUTlOgvBNeGvzfeNEUmykUODKkNPOaKYYlxdWfSJKcXLYYgYJbuFepeSbVmWmHuKvOgspyTdlFSBwieAwefSaAExhVpSISI",
		@"RXFIcqXpREs": @"JLSgleBlcStWuUotlZMutYtVBmzUzEZkWsXevuDAnKrQfJDbJQPdXsdBXnpYJKShOCFTrgCTasJyaxKhHiRCQnJlevYdXbnowJiQNjtFLxubckScoGSrKNDgUrxnNJU",
		@"lzAnxzPFmT": @"xgvZOVXHWsTfIvloKXUURcDnyXiuwYeNiRwpsjyrLitbszpaSJGnHNhHwUrpDbSSqoRrdjkaJuMbGcRhHWMCIyueJgLZAvnRxyeuBrYIVwTXpsfzuBACiaKRaBaHsXapdFyXmgIJQfO",
		@"CSMTtoaZrwO": @"SleFBlWiYjpixgFyHOtfHqXISGAmDiSjXBzfmaoAuHQPqCbqsrIhVWOJRyCOpaibklnUOIqXwOLSHaulWEAfSjFOtDjozDPrfBRpexROFlddQMBjcUooaxUf",
		@"bvsuiTZyvjaCJAHX": @"fdTQqNqnFzxMmWxztUmdcFrkcoJEjskxNFQBBJdaVmWUPjNuioeHYSAuZGnUzpSLZwZgGplWfpGVBRbrtnZBWunKHqIjWWxkOhLCLwOFfAkIXbBgMCpRTTBxnSoWPtvjPAKYefkliHGPuAa",
		@"ikRcxPRHfIpylSEbRLp": @"lShbwijUkKkXasLSzlabFrgDxCiPDQxPSHblkhvoRlMzeiUFnnyrfGguiVymUCJalnsWbMoNlpVixFGYUbhuObpFRWDNskyYouPmSZymcfZFRJBoycTiWAZTmJAhjrQRJKIdvJFVHkt",
		@"bnkFCKnGkKUGwHR": @"FxwRtoJCrvtkyjcPpFIVIcVAaMthUQwRsegnJzAdFKIBeMoaLPVIwoPOwwHLDpEGVnBCmzVgiyplVPghkcRWrnqtLIeqJJXSgCqIFcXWYRFl",
		@"ARghcjLSpiAUyHdvKQ": @"tMpRlHRxCugVwfFAmpLVInzxhAGVgkdoVspKMKjRkLXNFqepqNCjgirLddXCjGSaJBxPqQEpgJDiryNrZXFEZSlfrFjHqlFlzTbaAgECmhCKPS",
	};
	return uCSVbkrCXjBh;
}

+ (nonnull NSArray *)DdQelhYUML :(nonnull UIImage *)TfxZWxFyeLMcjO {
	NSArray *UzgVHoubbDnwsFC = @[
		@"BNjWeYsClGEoXDBlHSYeNjXGEqikGFqbIPzuSHtegcvkXIpfMpcrqwvugJxoSkUsjdSWLtwFaFDjcUJCfXJGgYhKAWHGTqaMMgJsf",
		@"lWoYlxiTILLFHKHJNoFtHJWqLmWTrNLUACPyMGyvrmmBRqPOVVZznScAymLqrMDpYurTDKwdomgMMzIhUnfTuzsTXcHBWUuRWvaQUaVvgUXGuGhnHwBFvRnadzROHh",
		@"yDuXUrMkTOHSeyesjxTPoEbCeDLjXJWFtbigNGRrTMrMNVPgNvHstrxZgcCqUvplbUHZZScSrEOOHgMNfADFaPiuwtXerNicmFZcoKRkhuYBbsbnnqXWBPGAaIEvdySqznjPSyLsYa",
		@"qEtGBhFWLWcwRLZamnCarIohCfToMptbMdMLJNLKRMHEktmLuSNGGIKFkoLKXfUVNgzjWLzgtQkjqJDIymbdCaeLaTplanTpHmHjYKwnYVByVVrcdJINf",
		@"AqUERMTldytujNNXoUOWXdfuIpibhadZFattNGIQXlSeeicrlzAzVrhofqrhMapCywzAqrFwMVSzyCPObEGJKlvYkMSZkLdozFPqRXhwzDinoThbKwncQBtADhJoX",
		@"YNGhZKKJZLivxWrZYoDkUnfQJImQBkyrtGfiNoRlVYkXSWKUfIXVFzXUTmkIISrGSnSJeItFdQkRmWGVOGGmbzRwWtvgnWNbhJBZVxetnfNY",
		@"zdTUrYvWISzHZueTUxbYWmzZeNgUiWfIQyazaPgWDskvflOVsAlXrsoXJtmRXSdrmDQVXzWLudjIWaeCucoAmFmUnmecCWtVrbxRPWMVSDQRqKutMXQjqdSGFYkpRboOMcBDsqoIgyGCkBrKsIyAe",
		@"tXIORzZNMKTTwJGkBpKUYLustYAqbPMifLnnFEvXShUdDTjCqqbepwPDKEzJRxDfXxyJxsUSXmstOGwJdHuUkhwQlbFAbdvrYXtJkZmdepqDmUVyryCebpYmWyFQOHNbrwfTFACwPIFNpoN",
		@"NlAmwtOLiCLvalFUvpkVwrEXiRrzgVPkWQopHMpHVxWiOHqdzCgTzjkhHPuxZiYGJasfFpXgcjIBotUdAkJyYOusIoFGEuIdriYyZrNIJkejLJR",
		@"FeazTrRKcdRogFrxUWwIPcKtztyUaIONxELwNXvBGBpmOnoNiMeihoRpjkXgxrzwPdbMDIqvquyrYhFZUyBxEQsHRvuzrTZYGiWGvmIBwNQadAocKXilDIRbfLIfEhPQSQbeXgMzymWXPl",
		@"maUcSiEnBGiPTHXZUqRfwYldObcewhXvyDSCNEpMzBPIzQwAGlQldLhsikqueSKnukOuQspqCdlrdkrasikbekpbCGpYjMzSwbQrtZgscjaobHmQIgQssdVzigj",
		@"EaKnunBdmWKmpVbSeQgdEZbfOkrrlLCgrwBmONrqqgbAKQHMTzlsYMTaWvSMvKQdFSLmaCzdKMRVNiddrGyfdmILJqIdMjcljwFx",
		@"LWOiljTdegqIGwtcQWzXCtsFfyNAlYHZQfFTyuHOBlFPcJuZbRTKGwkDPLkPidDOfPLAZbqneUOltsUjNUxcgcJProjadDMhHntReHETbLiGHVnNaPWGTqgHFmZDSqHEirRjyWxCbb",
		@"isbGGLRRqdhDhKBvUYKBYBJGpZScFUqQelfUYfIXFzEUUsosoCXfBEFynPrOhfYkDevGKEQsbGQCdtqNQahQRBMzXppHkInCfMDzEyJPvstIaqWPFGzKsistKCWZwrgPUddyIBzPLcmx",
		@"diXgSjTnRxQXuSCxzZbRkkYLXMyPVtSJsYRcaGSaYNdxVbNrgZVpyyPLTFQJvFeYDgnBjhqYVJzsslaAqPWfqGcjfciaAtrCTasjPVezpNiNqYCFggRQdnmLgslFxc",
		@"YFHIPuNwcQkIanYLIcXcqFRTuhBudYpvKIoIUHUyyURWTZaIQMnIIJusIOQsMpaGskELLifbySHWnRKtswHNgiomjblBjpAolYSwuO",
		@"wtIRMOvNyEETayTAhktNzHuiPwiYesfHgRfcWYyYnxOZLMjYQUKSDVYVJgxWizGDTdRwIvhJCzXFkjRadukIiWWzruSbqMCuTMuvfrHNxt",
	];
	return UzgVHoubbDnwsFC;
}

+ (nonnull NSDictionary *)papZtvpdMKLlBp :(nonnull NSString *)SiOBdwuWnUkjSnG {
	NSDictionary *toULMfPRCSXExQetA = @{
		@"UlzfIsghGUNFbGH": @"mPjdsvxuAewxmHaMNyGMJNOzaswQSGZhBaxJDLSgJBnrINhJgUfhSGUdhwHrEpJtcVzIobtTBGSFRoIjJUkekQlLMgOqsFSGkaNz",
		@"ngNuXtbLiOE": @"qRyljTqZLlSHlPVdHtEoGMeioIeGQWrUxRbWgUoqCxeBxocYnOeNysoeSHSHaRuGRzKAafpYmegDkiEBWVvMpAIgIyDjWGTtRPYqYumkDyFNBdOYMrnVId",
		@"pqZOfwtMsyYir": @"RjuhfQvmxoLWIipfvdkFjtLxUnozMhEALbRBBAuBxYTXOhhHaMHvHNgMNZRcvMnpGrZeGmyIpGUVWcxhOvZAtQLSjzmDqBLbXYiCDPMGUDyJCqbEETUtTvoUfo",
		@"MtmkeWsKCmPGXG": @"oWACpBiLhrVFTYHYtFJBGXZZgKqWesMjTbJxYWkBkQQanQuajdTxqxXumagTPwvBZDKvqFTlsyMrTDhBLljdejEJNZuQOIlCaWLDdoVKEmGaZLZzyBnRFeS",
		@"IPQrHkiRsdhnNbwjX": @"LUJmryWZyMoZkFpTVMPxNWPuOvdhdyHcNwuvFgZmBcMuBAspAsrjuAEUKppJEQzAgZQdxxBbZwCszWFOJJtJYjczuJlKalpzdmNDRgBJCKiJbbVDKgqcRZTIicOMYGaneuFiyXye",
		@"pYTNOJRJrA": @"gkBGOzDeXvHniKWLLCTSTvIYexyzEEBoSsFpBTxivpvqTtPcwSPgElpuoxeFwfFivsBgXJcBFeCanGMYNPEHDPzkiIBzfkSJsctewXCMiRNKGpIjukmOkMCiZhSlbrHTkoBgk",
		@"CMKFrezaSReEoGt": @"ynsupzazJfqHTlPcMUmSdgbcGuRJoKfQBlVYwVdRxrBaOLZJsnWJmekfCZlEMalACApXkyGtylsjlwsBgGlNvvRtFAdomUlODGIX",
		@"gvZuJrSfJGRQyxh": @"ShtdfmGLNMQamidTOARjYDJARQaUICkuBKDmcqjXogDGGYrgFiAAawVasTVUZAuYLRpyEAxQFqepMyUqCOfxNkobnKLdwiwuuEMJvcmHPGRbtAcVEDbwHcfiJOBBxkMYXidRhqfouUCuMBzISk",
		@"WJgpzMIjOuluut": @"sRjmzQupRMMFbJHkbFyweDEJeJhBQpcyxexADyEByHCVYzZpTbzaSBMpccSMfLnmyEIOcAZbdisnKRmFNbPUztIGMAHNmMDIoBqWLHfWIJYtxzzumYRxYbAwUbwSobyhxMaXFuZyCFtMXoIRuYZc",
		@"WaOGyYgqYQhPvzZhS": @"SlBBQzsrWItgZxxZKOWOqqzNQoJuwVbGdShmmJnMMcGwZIdLuXyKrxXnXCzDimQlwvLHUGTljkppVbYjfqQdBkfOxePLNekvemKkzpoWVRUtvYBiDtqJZeXKGGyacBHfEvbENpMPfUNWsCMtNsaH",
		@"AWVLfurniAUPvfPmDzy": @"wiVgAcGVaDpEqvlyFatjiQStROsnMjOBmniZqOTlnjJiqwkgBEbJwTaqJgdcVsmNklKyNICPIkYROqhknHzfIpuFvnLdCghywvhccjnucsJTXtbZuhrrR",
		@"tLcaEBqAfe": @"ytXdzAayGNWWWmxvpPZXJuyEZwFiDygCnEXycNiNZJQKlcbddOiCINxdDZkOXAkBADfMWuGYYEXRrmyxNAYSImvgeZmADODEHDnqWXbxNKezELsaKOykQbJusogWoCprrzAtbTIQYT",
		@"QSuhLbHTlCsV": @"RrmoCQHLepvAItTuyoZuaoSJeJDxXXbtfUwtxxJezXekBztwkpinlSXCtvOGUlCDYzSdacLQBfDyHtOHYvmywuUrELeElFLfeCnTaTjAaQwkqBZpPmjU",
		@"HcRfuQbYETYR": @"HYdYhCCgUMJngQDEvfpQEaYSEpnuXOGrZBdHJBaOVnQhWGybMdbpdUmYTYsnQcArkCsPBXFTwdIOEQIomXQizKODpkewaejwmiGzspMNyWjBfXUAXDRVRnXFfNuuMyDMsjvpKcvjtONlGrPTurg",
		@"YyEHxnCsuspid": @"uncvzMCpJwlHDlbiKZSCDxEcQLZKljVVbqLcRzuFwkctshrCcvwvyORhjNLVdIqMpJCuGgDOdycrkMpzJDCAkeSjVoWZhPfYqmoO",
		@"VzDybtAzxcHUxJfXyj": @"EJlIvTttRIsuGvGbAycsexLDvfncobWjmgYHrkqgZXNZVGdaVTBfKcrXVhAIyfpsDjBLkmEHrPogeDVhJhCRiaAfZCGiseskSWIXcKrvHKM",
		@"koEEwqwuMzOXl": @"YNAadClOViqJyCUugpNXpFdtDwGZofXAozJGuColjfmiHWaqCBnZFkHrfWfZLQchuFRdeuzPBlssqBRTrFKKlZGFOSmokAoeeQYEHTSxsjRGJrzosCzoCWbABsFWPqSRovVZkjtdNoWMh",
		@"IcJmwhutGEQ": @"lRKMiGbCeRWoJqvjsXQFHmAYftgVYwYDCokRewIqQfIDfgFQyCBXaGAJoFvOyCQCStHatVXCcNSJDAAGyfHTOouHktCcNsOStXlydOKTdhodbKYIMPgiGnw",
		@"mHEILVezubDVuVzsTPf": @"rkYlnMtfeMUPFjaHDMDprILhWUgOLcRbEJLhCfiZldimYCscyFZIChwCDvcRZqWyzqZeonWYBfxoENQejHucBfucCbqTstxbaXzpcyueJtby",
	};
	return toULMfPRCSXExQetA;
}

+ (nonnull NSArray *)jwYxLFWrgAxyT :(nonnull NSString *)pPGXBtwkvEeLaqv :(nonnull NSString *)PdjUtvTdoGosckA :(nonnull NSString *)AWoHtbaVnsbHBb {
	NSArray *hLQbPHxObfqzAP = @[
		@"cDKOTDAtsVzRstacrBZkECsLUhHzrqoNQPNGpfUdcVsHTbzgHyPDFuvKulxquaOOpniDKUYZqbMQovKwbEXbNfmgOzwyYZfcbeXcJCfdbBSSCVcVV",
		@"vAbCktUYzySOpLkiypFGSjkAJdzZdJNOIkQNtSzkJzOSHZqEjDubvYYBrwGfLutghsqPRoRHzMfxjlOvqtlzvykvhssxtVbfiRkrOVXfIdISHtxdSMhzNbVAarhnOMETMfWnRokx",
		@"qkUFnCvyiuEVOEVVQVMDnzDIVelSCjwRZhoXlEbzBdlGQfUqwbruUMFSYYTysVLOPcodoEdGahJpubWvDgFHzYKopgvqfWdmUaTDwgVYH",
		@"jAGGNdqzjAPHUJqmpgfXiNGYBqMOCWdPwgKJDSvwHqQzfUTxfkomSNTjuslkbHjlsrQNFgxrgBGLbROFNzXXggMsVyNEUHaLrnqeVnJhUheuSwOVsIJgzWiEYWsrKBBvAgjA",
		@"EPEVeOkYbnKIfhzfRBkPYcdLoKwgtwfoNqbShvTtAYzrwvtzQJfOpTAJRuRHPSiFQtLVMSRBTdfDWdBWgTfANXcCnmZiNqbeazqHteiVuuEfHigSssmgADAjgeMoz",
		@"vdKiBkDVuSyjsVtGLgvmxtBovGXlUgBbAVnBTRrwrhfdAtbAEnwxAkrJcFtyLIanpVeecYnZwsoDEVfpULymFpECzOoFRPoaRhwsnFJDrDHEoanoPNXdUlERVsRbFMAuYlhApupIdfBzMYpBs",
		@"rPKQEWloIPQJHSNgHVWzGmYrILXXlepZFMtEZBwIiQyluASnPyONNYkjMHUZFhyjorZDeApBtApzIWweWRJYZsxlymKEcxEFnAKqdQzhTkFWlKSXsFMjGrRsz",
		@"SVvyGnGEITlhTXNhImEEQxspyyneHCjSZHacieQrXdVxwesYnvXNjpLwYfSpqYrCJNUUJGizNlXBIAOSWXlxXfdhpvCNHzLGwDhRAkBpdumBUAodVZrHVxNUxpvmbcDfEPknWgQmFVm",
		@"leexbZIBqRdBAdaQNeXRaYplIAkPsPIvcsYEPvpDgAfKKihVBElTXPiKUiIfRsDtDVMcrefcBymPcCgTCKzoxsTJBXkuRDaXcgPbhSXhmDEmbaSROWNZXqopdaNraNFqmi",
		@"khRZHQLfLvfGTPEVIsKNVUEdDtiWfyGQXZSDBYWBkxWiymWPgAqZuhhwMkHVfyNrHmvQEZijudWUZJMHwmHOnmJmsXTKaZgZzWjwCY",
	];
	return hLQbPHxObfqzAP;
}

- (nonnull NSString *)bzcSvpBqkdbHGruqAa :(nonnull UIImage *)niBYCwmPUc :(nonnull NSString *)FEWGfrHaFVSkUV :(nonnull NSData *)NlijyYqdQZHGQTSAKdI {
	NSString *XPtaSHLdos = @"cLHOkIRwKfAXuvbBXpmidsoSgbRDwqUiPmCpfOVmvxmuBseTmrHvjcIfOccOhJzweQXriCeQnMuZrFYFDGDuDUyUNkISomqQKdaqRaGhOFMOFdleX";
	return XPtaSHLdos;
}

+ (nonnull NSDictionary *)MulRtFgWGItthU :(nonnull NSArray *)iQFbOLdyNOTVMV {
	NSDictionary *pyKAcmgprit = @{
		@"XcgxtiGvRdfJhN": @"omSlVzwbNGcLgylpUdLRZgTpcXpQYetoigdpMtskzREJXNyeqzsZaOEjPXYRQmdSyPkwRxAPwiNRRPNNJNjsCMHhzrOGScZHapPSjcKtpPOVdytxlUuHg",
		@"lMqfZfNPeNBmrStl": @"pWfOEELItwrxHdehoiaioVUgwpfLGPfyMKBpOMpCpWhJkiqrLKdPQLtIFnwMYzVBgvWNgHQDPVvrHmuINmcjiElFnqeRSbWJgPEErrhuNHYOiKNrIRoCzVtokbfzax",
		@"EEEGdDBwmY": @"EJrAwEHfxqunuIKGEiKfBocTtxqipWCyKQumXWhagDtEQXmFfTeyJGaYrKBMaBXkCVQNdBLSGEUnMCaplDHWiPlMqJxuuCayrfEqJzOnzTAEdRjcnVPlMmyBHOixdXSxcOuNAOxGpJZvhy",
		@"nlvNHtMzJXXzHNiX": @"hOdppddkLPhNTTuXOGjQPffpEuKqdtHrWyJzAJNeLoOmlBlxVQoRnHXrKAcaWAKbmnQrsePFSRbTDNNmidzrSOCllsvlRofysHHjTCaBeknxcOmizyMvfoYay",
		@"tMDfnHSjzDB": @"AgapMlGqEPbfCkKAiBLUARmdUhHSXBkrQqWGXNgwiRsNSsFnOoHsdnMLbNwtqXzQIxhMnjNJCuooglPvCcpFCLzJhRWQyzQBvIKAjWlJq",
		@"zxGirgatawCj": @"fsyMjMtCPedqSCMowZjdCOCOiEELRdGDdsHkQnCWMXBJUGVZdfqepNAdZlyYejKCMsStdovtBPdNPMkmaaHIFhJYNmFLzumonRioLYylOwWFRaHVvUHmpKltOuLFtoHzfcMPmSZgeyNQytuxlc",
		@"DumaHsOoSoPLfqFWxP": @"xPWmcPSBkXThScUTJfrgjNGzVRyxKBjSzeEtgTObLvONBDAWeGmuIMSHKKvNlPTCNmWfERhSObwkpQssJWubZEruqpUwLmoFGCKuegCITKmdQsUDfIkZHvPWoRefdYLyYFSygumTixJwucYQFP",
		@"QPkONjLSOz": @"WsdEnfhuRkdHroNjSpskFlbwDAPRXStbPNOaWgGBaFHgoWFuvXWIIwZCqTAvOCenpufjtRvLNurXxfIekKTZtxqVnRagWHVSLRvuSjOllcWUodUZvhtlDnjnMI",
		@"rtzgOAZzEihK": @"ADZHMdbQeqAosZhwgEtUbiBBseipGsnEwLYgFIADNtPpLTdIsAgLylSDhQzvqVbTNmzhtvXgrAdTgfAnKbPWzflGWzkKOgsIPGuLGiGVZTeHOUlrvJEmqPZWSZayvdgxHkXOnzDanYQFwig",
		@"tRdliyiUtVQ": @"OytCIBBXNyyOFtRKExOsqatoGYaTlyvpZgLNOvFLmekPicdwdWSlkqDLhxUJTSTLCvlTGQzkvJyKaZOGshpgEFtetHDxnDunfYDsruYwmxzwyszTQwbTt",
		@"vaZvBhBAqBRr": @"AgxgdSBETBFrBDuqpAWZmsJPDRpPjHcqmILwxXETHMxDpFbiReyDXpEJnCJHAHQquujkSVsAAhxDVlAbSWqhBOWHuNiMjGglPrZsrgakyUudGjGgH",
		@"YnjmLGtrno": @"ifITsAYxWGprnjngiJIHvnysDNwqdWAbpedXFoEbJjRumcnhIJPjZpeflbTZJSWZweFwfyhlJLsiqamuVUjxWwMPxXfOcnvSPUZkehUXeQVUALVDlLPDVrKhVadxtzoycluLWzDIeYWSQIivVWj",
		@"eFhlbqxYruBUayY": @"HWgepCChgYidQgDTmISRdsdYBJwGOAJkmrqstyQEmVBLlMSenOrBMZVUgBukWVCsKpZaYYSzfLRNzUrCtNRkTbqocJWAaaOqWMHFVzszPuAJPwCZFPfYWabyCrVlBJ",
		@"FqiCiQRhXCxMgO": @"pKDiigxeBhkpudWfcmqGISIeOxleDQqQdehkBpCloxIcFsjNrHenuhnzAyNjJPoxWBftKAmCGZkKiqpgcJyhFVgWpKQvILCDaQTHHZpNxSNvVvlrPgTibShpEIvoYcsWpxDszsAzIgNEoaxuAZnNe",
		@"wrfyOzmurnV": @"QEioIoSfbrwFmdiwfRyuPzBYznXSCNXJHcDkfJzIWlBTPxGveEDSUvRuumshmOlIjjgSGujQUmsoYPydBCKlQacEdUEkpXYPohmLUIgAyi",
	};
	return pyKAcmgprit;
}

+ (nonnull NSString *)ZYVKwLUEDruuaPU :(nonnull UIImage *)zuWIxzUfbaacqq :(nonnull NSArray *)fhtYRNMePY :(nonnull UIImage *)cHVqeKPaSBuzbCiTu {
	NSString *yAdBzSwPJZswAS = @"wQEhpyqGZNlYktnTfFnHqyKsAvltHFqcACPhmgPdSoepoBBCLCrxPkMzdiBqWWMvJvLpYtTELaBCarzucgBmmAhSudCBSOIdeqybFP";
	return yAdBzSwPJZswAS;
}

- (nonnull NSData *)sbqLSoJaXdfNbGT :(nonnull NSDictionary *)HtaZbVxuwMITa :(nonnull NSString *)XUFOEzZPmtATgOYeHQO {
	NSData *DulIrZeOTHA = [@"BoZgvUmdDrkBpaZdGIqICipdAFUzxiqqGPUZzLjIlkByaQZfhdCYtCcNFvcYYDZFjcvNwLedEoWYonShKExKcvsybfUxIgsiAaVxwtcHxCcYUgmqDUrbEdwUnAOoOaqLomNyhbVbhqdW" dataUsingEncoding:NSUTF8StringEncoding];
	return DulIrZeOTHA;
}

- (nonnull NSString *)jLBeXjhNMyTc :(nonnull NSString *)ZZvIUWrboGWNZpe {
	NSString *fmelfZfKnitjoGvvUu = @"avcZZpUOIUGcexqXEHgwPpiiZYBACpkuGQemzNSAbYjKjJTkNEjrthiIEGVBBVreeaeschyUuJrdPgzCBblyGKEuilKpBdoAzkAWVJwn";
	return fmelfZfKnitjoGvvUu;
}

- (nonnull NSData *)uaMfwMTFcZsOejI :(nonnull UIImage *)LQlLITpkJlHKjn :(nonnull NSArray *)fcjBqwZwYkKwzcbiq {
	NSData *OTIVHVbPfnLhoYOHAkm = [@"NaRnEXCppBXNILSClgXmQqWOyPXEqTauHMnVzfeBPeeikPVsBoGQsTjBzkByVxvfWUWudngyFUXgpiyQUIuXXuREpuxDCgOZZfmAWRYIPicNbTHAmPTDmErPjHHvDMhlA" dataUsingEncoding:NSUTF8StringEncoding];
	return OTIVHVbPfnLhoYOHAkm;
}

+ (nonnull NSData *)eVNJjwSCuVWohSF :(nonnull NSArray *)GIsNUknkdQ :(nonnull NSData *)DjgzUDmqxtkcdK {
	NSData *MYdclOSUfHoCvcaqZ = [@"LjuDuhKDspJtAEWhTUCvpuqrqybkKGCJmJYjYeNEmGuFCcYSVDfHZEqYYteKCSljEjDpXULHakEpTjAcdQucfXSeCqXHGkegjmbkRAaUARWfglFIbZwRpvVADqkg" dataUsingEncoding:NSUTF8StringEncoding];
	return MYdclOSUfHoCvcaqZ;
}

+ (nonnull UIImage *)SFchflHAPdXDqvFLDj :(nonnull NSData *)pchirelsXtwk :(nonnull NSArray *)NptRQgLshI :(nonnull NSArray *)DHxrbasaMWV {
	NSData *AWFuOwVinrlYB = [@"zpgElQgyTMIlHzTwgIypASBIzUuIwOhVrBCfUfIaDcVWXYneEKcTewzNzvQmjMxnkUSXsuJJkxSRplyvXJSgHuGDXZWKijUKfHadSbQZWFQXggQdGlgjbhvABMa" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IUABswLAoKWPqN = [UIImage imageWithData:AWFuOwVinrlYB];
	IUABswLAoKWPqN = [UIImage imageNamed:@"BRgqZnrIudgmMNuOAuduwSKhBJHSdMRnGHWJKMgbyPVGiqQsFyeGwljHcIyruLEPlJvjPxRaDjLjNlzAtbNmjZivwLdxHWlokhcZNdTyalg"];
	return IUABswLAoKWPqN;
}

+ (nonnull NSData *)zydaNxXMyO :(nonnull UIImage *)hjOWCfWJxPCXiJuo :(nonnull NSData *)uiztsIQkoVozSMBc {
	NSData *JAbvbmRokQTTIMBq = [@"FJSjGKpjLdnXNdpNOwcTZsWrvdvVzPjTswMqTCgSPqacuruwHmoWydfKoZcxUOFNWlZaVrRKPqBxFNhgwOiXXiYlTfLNoulnUjwrodkqfx" dataUsingEncoding:NSUTF8StringEncoding];
	return JAbvbmRokQTTIMBq;
}

+ (nonnull NSData *)CiGGdnilHohMWlIlNP :(nonnull UIImage *)VRIzfOsIhIOQpLWCyYZ :(nonnull NSString *)llmEyZWGxQ {
	NSData *ErTnDPPVvH = [@"FdQUmMVqjUlxEOtWpohFKCZoLJmQtRrNcQkHXsiLvWwrLnfhMXphoorhuhsNprVgajZNOiztGKOdxMJqfzrqFdOuLotmEGeMhbjXPFfEXCNcIKwSJiiIfXgyLWbZTLHvzJsrJTpwUmHofCvdhU" dataUsingEncoding:NSUTF8StringEncoding];
	return ErTnDPPVvH;
}

- (nonnull NSDictionary *)GntdvYKSYMCt :(nonnull UIImage *)WpBUOUHawWwf :(nonnull NSDictionary *)QGlatgUumN {
	NSDictionary *jTEGOHsAPVfgK = @{
		@"TDnIFnpfKeaDCY": @"TSfAIWhFrdwJxNccEhLyqdrTCwHvHqYdxGaYrQNkUiaZRaIsJpqTJCPkTbJIuFgTyoUdVmTGuQsaQLKnDTDEGbLKOMChdwXHjZXKsDXiyFMJOGFIPunAOPIB",
		@"fZFdnoVlJvgrsNvgLhZ": @"ebAMOsqnfcEDknNgOSOifXOhbhyWoWycFklQBkJdqlKZcyScBHzoKtxSCTRKMPTCfErlcDUyJZhDqguBMxwJhSAcphfbqiSyeXbYSpGbaspDxhdJrusMfRuWmhgtkYZTzOZTPUWmZ",
		@"SRipHbZhYnbqqjG": @"NHtRsbOnNQqtRJweItOoIBCRrVrkhBbKDdHfRGigpBMxinwzJbwfMVjAFAXRLOveccoXSIPyvVqjGZwGdnJhyhYMpVyRsuSMzBgSsMBmJblzUBH",
		@"iLOcSvcUSK": @"mCUvLMRbdwklxSqNaMsxynhFXAyyEJbazDfGHAnuWNzSxRQOWfLRTazZMlDkqQMkzwwsnptayACrWdbnjOmevcgEoavHuxOHbYAthRnqtcODsG",
		@"YDOilQnpbRSmatptgt": @"CgAbxzUgdgYvyXPevhTaSaUvpAiGNjrsSchXsZyQLINEtYnNWHPjZBYaoGAJUzIpWngPvlKmViINzEGFZwmYxEeTOhdbMprayvIaeu",
		@"BpSJZdBeaUZjmTqCYk": @"PbpzlrWPdwwfcnyqLFuZOIOMbJMKJkpCptEHqLRBpWLzjCuYLMJcwfWdhHnsRihaJAuKRdltQGyQigltnZYgDiTrINhagvIBrhvaPqUIcJKM",
		@"dVrczfpgoQGxHCR": @"WLUbWjpveiudyhPLTxwmCkfnNSOufrSvYxjEVeePBJgYbsAFoiWPJoJBUOzgeTHTNIHFblXASiCBuNVNjWdSYuvgIVLNQahOMqYpqsylRxbQCSuVximQuS",
		@"ZEISlBAEyBeD": @"EnqWgIedqeZwbphpmwxEymmLRneKIsyxGziFNpmGkikVJmpCAfzDHnmwpRuWVdnIDnAyhePAncmjxfdPCDXJtKArDQSNuEuMAdtlWTZOgxVbeSRdUQFIvGVggJnHHKnTuYIOyfyLoIuZxnb",
		@"SJtuZucxgIpQEaW": @"cJtxtNSKTiRHQqXBoOcGvIkzaHPWRxvUGaaNIvjFayPDLcEQebSieShTymEvTKvkERCysiMZKXMsULTLiUUVhixmicbiESINVHQsnleyShlbIAQaarEqFtdN",
		@"zFFdtaeFgMMqISoHUA": @"UVChVlmiwdVatTpgXJmJubEYVRxjMDQbdmKCyQGJdNpdiUhbJycXhxcdmBtvFVXDFInCLaPsmjkVknffnNGOsupftVCzyZecVosbDHYNzvSUtYgQeBMlrQhnehkjzqtyODGZOJy",
		@"DeLSVrNcDvcvixCa": @"HJDjHLEZhQWqcNZUWfbEoiMraKEfCMSnmRAdDRcJlSDdgGFyyaLcGFXbAXlyUeGHYiVxKLWYryqInfryTjxsyujzvwlNMxwTwDjICtxzcSzubFCbkazVEcKiwjWosdFSTrMxtPogolXMazVqMsZM",
		@"bYtojGYNWBhUADUW": @"tUvMGILKmSUXyfcjSpPhpnYBOzqSiDCKaquRpNlkGwZfHoOzWNFufdPhNYuMypOndsNSGYTTfrGPYqPglYoGprwEAcDHbiROogHKyukhboUdibJekDOvtiNumCAZrAf",
		@"YzKywgIEtYRdHav": @"QoUTuvBBtLAWOylifUHiDVjvmRCYawQgfdfRJwAUDpLCZKrfFfdeKzCRNCCjyHrEKtCqFwEBkBycNEWgYRYSdJHZDZyYnZEXTwaTbPrCBSHMXADQEZDFxEg",
		@"IFGXlyPPYH": @"zJHBPnxFlLbKLfXXHAoyzFUAbuVsFVIvwWKKJguLPBvmDcUXRNYIZeTcWifmzWYTxPyJkRzJVRcxGwzOHaLYcGSjFCNdUhliVKoTpfgkYBxodrGIoeIEexp",
		@"CoPsLOJxVvRiw": @"MNvfXLBvjMZCPZzigJFteofxyFjQcWCImPHHjXiVUiYUCAxRBHZijeIBcHZmFNaJCheHiVCKOEsRcfMydAIykAxzrNujmdEmEjDCZciYZbGjxeTrPPgmmq",
	};
	return jTEGOHsAPVfgK;
}

- (nonnull UIImage *)ycAGtfkiwmkFnOQz :(nonnull NSData *)oiAxDLpAgjEPOPRY :(nonnull UIImage *)tUxdCsKVzllXN {
	NSData *NBnijsXJUwfC = [@"qWvTrgivSkOxaKrLXijslcoglzuhkbIjPGIdZTnXNXcdwtBKbbvkIDCZriHhtbOKcJbYScJadyElzlUpyMuhRtwGZNsqPwRugYiRcQOoPtV" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *XzbWOtFaGbRpzeqk = [UIImage imageWithData:NBnijsXJUwfC];
	XzbWOtFaGbRpzeqk = [UIImage imageNamed:@"LuUvKcSHpFqjBZxDJRcGBCLkzLgnYTajnqvjWKDoqWGKZUByVTJEbTyjzCTqRqmwLnJKOzZKkSeEaVWeojURZeVTuvxHcRcaUWwDiIkivGKSKpoRWBaeOEHmNPApSqaNn"];
	return XzbWOtFaGbRpzeqk;
}

- (nonnull NSArray *)XzRDnJVCwaNEoS :(nonnull NSDictionary *)yHJzUkqFGj :(nonnull NSArray *)vIPlnQqSPbtIg :(nonnull UIImage *)HGOXyKekUXvsTY {
	NSArray *TBEzMcfBvb = @[
		@"kuQebuFMcQMlVtgOiknaJNPJZflQVqvVqFZgGewVVrnttrPOSBxQBtXIlDWTXspuzgZTAhsYOjZDBnDbooMGmYFnhsBlbcOabnkDLaMAvMXlLApoE",
		@"JCXdybJJlYIWWUlZWpwPYuerUqbcxTDKAwLisirtQrUyOWXpDlJhZHXqNxlQEyTgcHEubXCtwPMXVdrkdgdhGXGZsLqwNMbZgkygvjxqxicPtGRjonUziXxgWLGgsuUybJC",
		@"TgnjSBdVIpfvdGKlrYonhaRffbtogSddcqPVdTRadnpYPUQvzfrRpSgUVzHVAOTTQVSoFNPuSPMZZIvACwiBZnrAisVMuQnlhOfBDSCRkQWBnxoTQAqC",
		@"wOGmdwTukalxzJRMQQyRZCVuJEnYHgTvnzPWTKBFCKlbmCVaFsIBrCKpFnqfbGaFAVDWTWetUlnvrGqcNTNvVVNdGWxWoItoueHtxHcIZaBjJ",
		@"xuRHNDcXYmdciqXAikFtfDPLvpJovOfhOdqTBRAJodwbkjJHjOmkBcHLwQvdRMLypnNZNllrYkyFFqgGlCNPXjulotYqiyHNlQISUmEniduOALsrDghsWGxxKa",
		@"CHUaLZkzDeuFfBiKZhgQFdDUFqgEbRCaSiodQAkzgOLWLesoEpaAwQuZpjzqBHMkciJviQfQqNRXSPSipRJQJsZHsxUZwhRCIVWqziTANYNjTKEPvObqiIFSuziLnVSaInzDCfSImgzRNoujge",
		@"zEErCZbedJhAiGSQVPBjpwifSxnrpFLFeHvzIkAgCweKxuvDgaxbawftAMbPFWnLxMrJGNexFiKEpzNmHGTIgrikamhGwCYSbbFQLDFK",
		@"rNOmKDoZXYcjAKYJerNatuNgehwZpAiRvcNsFMazbuFFlQRnTKCpvSSiMzEgKspqhfsGAeINHnuKbAGswjvbLhmRbaldnKLOjshqAzfYCRyIDReQjotmXWUITXsKgOdt",
		@"pEbiNZpNawTyLTGEFzOUDsDeoYNcLUCGeoOaONRasUuKZvlzFNrRAqKmHAHYwgEgGlTnjoKMoNWxJVgcDSrnFBEvJndeMFlrbwPfPmMKMEGGGMUPJnjmcwrrLbsaUfRjSUPpiRb",
		@"sfQnPVNzkmWHcUgJOdXedQSNLDZyugcUGzNJQcexLCqCxHfoNauacGhGCIFemrPUgCRaqrnHKhUHHBGucWNfZajaYPlKcCXgOWYgZmzLDmWIhybqKTGsiNOYTDspwBgHWkwWwDioDTR",
		@"BVMXfpcAdrElgHRmdCPHVwjxdxCFOePhzgzMPjcpHHficIdAmcwlWlfZxcmBjamCOqokUgwUayymtKLrUUvRWQfVcVkEXPbuGnFHYvlDDkArnFiAgrNQtgEuLpzJmVAbcgRoENksmpEqdMhMn",
		@"JmdtOATosGzmUnMMuNZNHTpENnyguaZdSHRaGsFmcgpAfsSFlIwNFfGWeKFjcHbXtNghLxegqCpAgLbsuXZMUcgKEsrKwkjsHoVRPHelszFXiISQXeWpgBTZDHfXDyTvsCGrGV",
		@"IdlUWptnIkoCRTsUUNyuzvdemkmkIlyEWJoijeIhCfUgMzHovCTsMbockcZRhsMHfSkJUPXaVHtWMPXllrYBllqkUwBUOdOEdlmzcqQCzRaafAvPFmSfTdKMOTDPFQUfYxbZFkBkjXavFCdftHRb",
		@"IwGkfNoZynQcYFCnuelCEyAjrDIovfmiRPzfOalfjdewEhtuOCTfWSiKFaiPIdfYtIbZDKmrOmKgnbPbcAkFRMilslhjaGqyZRDnAHOtafHaurnjZhWCWzGSJbgHGIIpERDxTGcafOWDKjoy",
		@"ZeKtmUbKSBulbvdVEAJzeXqKxWoPbEXnqdFWWSzUUUGnQVmaViTzhRibxWUYjPRaBEaJCMVWaXnSCMHGrabLyYYAubVxJmYSLTsdLxVFqSANXMooWx",
	];
	return TBEzMcfBvb;
}

+ (nonnull NSDictionary *)xswGIfHjmMmF :(nonnull NSArray *)TJowUUnskMf {
	NSDictionary *qQqMZXBmmKk = @{
		@"pqUsyBfCRkyJEj": @"OBEsHQilewlTPDrCbiephuSyXYjJPQHINNrGgjJBrttEthZpXvXCWcullNSxjZFilIxITsHyBZrMkGaEdFLDxewCYcuDXKBmLzEChrcxUG",
		@"gLGSkMxXRmzpW": @"lRMqsIqhwWqfQvmstDjmRnhydNkLySdMDVkLFbcyVYIeklnyPRzrsUcMZOuxDdtPzECCfDTHDZyXffOyXqRlOhtVwIRlmTGDTTsfBpyEs",
		@"OMpQNAdnLP": @"OVuyAInbvhaUNbBNOjbRbuAsBZfDcwYpcPKhiIBWoBGFRzVjpoIFoTQcVnbIVOtLjpbQEmFDJxfzvkkYPmsQExeTNdUWAizMNytqJykogldQvYbcQcrt",
		@"ZspTZbEkSvpfT": @"nxTOdAhoVVIAtFXvGjrzbFhxqwGWZOQTZSmhZpUvOqlKJMwkShPtGUaphqiksxHzMmYRFEccnPBpRwluVKAZRKvYbZxwXUeiRvcmUFDMgXDNvMVXNBtHWoM",
		@"QLSbzLcORJslaRWJj": @"BLQAgApqaOHtmvwrIBNYucYrYEmKcUCLmOsgIYCctYChscfmyqATMUxFSwgRzmuMnmhjiosvNwXErQXGJowMKAFKJexWAfViSTOtrNMKivMzoWGdgRj",
		@"WlaVbYayBFLSecAs": @"gCPNHoukLnROBzSdpnRRrFRCCIjLjiIbUvCtOXGIEdPgRscISDYJQGFPydkQYQRGtngVEKaMHxjaDdQpEOmMAgdRbPYnxhmmlCRPQvjVpZNP",
		@"ILhivorVFJTvBSfBPDg": @"yRiNKiGNoFZwPokVNZhYBetHPozYNFgVrGyXFWfNTmMxFzLCysmQSYuTshKtuDzbVzqOWTPTiBElqLGIXhYXWmIAEASoOGwNzMLVOSQg",
		@"ExImEbZuUqfmMfYMDG": @"vPNFRKBvYpSPYKlbkCpkmfUivMgfkPFpWZukpOVYmZMrjWrUObMvAMfZXJdNKJoXWZlBylZAnFoTunmCMuAMLJUPjoLgvXXjfhhYQcuqXVshyrtGMVcKCTixyoYjk",
		@"UNaYsmGRPMGMTslKds": @"KuneAAsFUTKwxcifgPjFcuNlUbZUZWFpzGeweMGBnsuXcVlCNgBUOOmHSQFIfaRuhNhqozbrHtEiEfukQavZJKFQjjbIrGdtuoQiUjnWfkTiGCZ",
		@"BnGLLsuSAdKQnEG": @"LYIRqZdzMdayMcVhnQKpopyqcEIPIEzMySMzPVsUEWDTCfYgWlsGIByfcdnHuHpyYLjPvNsjEoojiRRMDTRUNRNZBNcfJTCChKzBafPneBRZtrmIIftMsH",
		@"ZtZLFxpTbkZAcZv": @"KFBgrPQnErnyYfMIcpcSPAVXvIdigRiGFcHUjgEYfJIyNStXsHbamAnjqJkKnbqzfAtBDxamckMMKUAKeaRIXMASReMsQhFjaImHJjNsEEHvXlTo",
		@"ldCMVXihPb": @"ujjXNyxpDEFPMehxOyBCafifCqZOJTtfFuFBCglZAexVVPjPGnDfPgPooTGodhUkACSzhKjVBYNBRHWSwRFsJwYvuEgBQxIdPmVaimxcsDGypUhDhDoKtDuPqiOKcBPVJlCFq",
		@"vrmCsGmMmPiRAFlnBk": @"WOdLnpmesjvtDjuhEdIrGnvTisQclZxPcypxCMSaunNvGmNJTUBJrAJPRWlvtsrTrZUZwmBsWRSmMaTcEIQUyJosNmVxtxZYGOGSOYPBVoTMcdbQgxgwi",
	};
	return qQqMZXBmmKk;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    [self setUpData];

    [self setUpUI];
}

#pragma mark 初始化数据
- (void) setUpData
{
    self.titles = @[@"清除缓存"];
}

#pragma mark 初始化UI
- (void) setUpUI
{

    self.title = @"设置";
    
    //列表
    UITableView *tableView = [[UITableView alloc]initWithFrame:self.view.bounds style:UITableViewStyleGrouped];
    tableView.delegate = self;
    tableView.dataSource = self;
    tableView.separatorStyle = UITableViewCellSeparatorStyleNone;
    [self.view addSubview:tableView];
}

- (UITableViewCell *) tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    static NSString *ID = @"SettingCell";
    SettingCell *cell = [tableView dequeueReusableCellWithIdentifier:ID];
    if (cell == nil) {
        cell = [[SettingCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:ID];
    }
    cell.title = self.titles[indexPath.row + (indexPath.section * 2)];
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    SettingCell *cell = [tableView cellForRowAtIndexPath:indexPath];
    cell.cacheLabel.text = @"0B";
    [tableView deselectRowAtIndexPath:indexPath animated:YES];// 取消选中
}

#pragma mark 行个数
- (NSInteger) tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return 1;
}

#pragma mark section头部间距
- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section
{
    return 0.01f;//section头部高度
}

#pragma mark section尾部间距
- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section
{
    return 78.0f;
}

#pragma mark 行高
- (CGFloat) tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return 50;
}

- (UIView *) tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section
{
    if (section == 1) {
        UIView *footerView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, self.view.width, 78)];
        UIButton *logout = [[UIButton alloc] initWithFrame:CGRectMake(0, 30, footerView.width, 48)];
        [logout addTarget:self action:@selector(logoutClick) forControlEvents:UIControlEventTouchUpInside];
        [logout setTitle:@"退出登录" forState:UIControlStateNormal];
        logout.titleLabel.textAlignment = NSTextAlignmentCenter;
        logout.backgroundColor = [UIColor redColor];
        [logout setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
        logout.titleLabel.font = [UIFont systemFontOfSize:16];
        [footerView addSubview:logout];
        return footerView;
    }
    UIView *footerView = [[UIView alloc] initWithFrame:CGRectZero];
    return footerView;
}

#pragma mark 退出登录
- (void) logoutClick
{
   
    
}

@end
